import Foundation

private struct Tr {
    let zh: String
    let en: String
    let hant: String
    let ja: String
    let ko: String
    let es: String
    let ar: String
    let de: String
    let fr: String
    let he: String
    let pt: String
    let tr: String

    var dict: [String: String] {
        [
            "zh": zh, "en": en, "zh-Hant": hant, "ja": ja, "ko": ko, "es": es,
            "ar": ar, "de": de, "fr": fr, "he": he, "pt": pt, "tr": tr,
        ]
    }
}

private var currentLanguage: String {
    let candidates = Locale.preferredLanguages + Bundle.main.preferredLocalizations
    for raw in candidates {
        let id = raw.replacingOccurrences(of: "_", with: "-").lowercased()
        if id.hasPrefix("zh-hant") || id.hasPrefix("zh-tw") || id.hasPrefix("zh-hk") || id.hasPrefix("zh-mo") {
            return "zh-Hant"
        }
        if id.hasPrefix("zh") { return "zh" }
        if id.hasPrefix("ja") { return "ja" }
        if id.hasPrefix("ko") { return "ko" }
        if id.hasPrefix("es") { return "es" }
        if id.hasPrefix("ar") { return "ar" }
        if id.hasPrefix("de") { return "de" }
        if id.hasPrefix("fr") { return "fr" }
        if id.hasPrefix("he") || id.hasPrefix("iw") { return "he" }
        if id.hasPrefix("pt") { return "pt" }
        if id.hasPrefix("tr") { return "tr" }
        if id.hasPrefix("en") { return "en" }
    }
    return "en"
}

private func localizedTemplate(_ key: String) -> String {
    let lang = currentLanguage
    return strings[key]?[lang]
        ?? strings[key]?["en"]
        ?? strings[key]?["zh"]
        ?? key
}

private let strings: [String: [String: String]] = [
    "app.title": Tr(zh: "Mind Cipher", en: "Mind Cipher", hant: "Mind Cipher", ja: "Mind Cipher", ko: "Mind Cipher", es: "Mind Cipher", ar: "Mind Cipher", de: "Mind Cipher", fr: "Mind Cipher", he: "Mind Cipher", pt: "Mind Cipher", tr: "Mind Cipher").dict,
    "app.subtitle": Tr(zh: "MIND CIPHER", en: "MIND CIPHER", hant: "MIND CIPHER", ja: "MIND CIPHER", ko: "MIND CIPHER", es: "MIND CIPHER", ar: "MIND CIPHER", de: "MIND CIPHER", fr: "MIND CIPHER", he: "MIND CIPHER", pt: "MIND CIPHER", tr: "MIND CIPHER").dict,
    "menu.daily": Tr(zh: "每日挑战", en: "Daily Challenge", hant: "每日挑戰", ja: "デイリーチャレンジ", ko: "일일 도전", es: "Desafío diario", ar: "التحدي اليومي", de: "Tägliche Herausforderung", fr: "Défi du jour", he: "אתגר יומי", pt: "Desafio diário", tr: "Günlük görev").dict,
    "menu.daily.done": Tr(zh: "今日已完成 ✓", en: "Done today ✓", hant: "今日已完成 ✓", ja: "今日はクリア済み ✓", ko: "오늘 완료 ✓", es: "Hecho hoy ✓", ar: "أُنجز اليوم ✓", de: "Heute erledigt ✓", fr: "Fait aujourd’hui ✓", he: "הושלם היום ✓", pt: "Feito hoje ✓", tr: "Bugün bitti ✓").dict,
    "menu.daily.todo": Tr(zh: "今日尚未挑战", en: "Not yet today", hant: "今日尚未挑戰", ja: "今日はまだ未挑戦", ko: "오늘 아직 안 함", es: "Aún no hoy", ar: "لم يُلعب اليوم", de: "Heute noch offen", fr: "Pas encore aujourd’hui", he: "עדיין לא היום", pt: "Ainda não hoje", tr: "Bugün henüz yok").dict,
    "menu.classic": Tr(zh: "经典任务", en: "Classic Missions", hant: "經典任務", ja: "クラシック任務", ko: "클래식 임무", es: "Misiones clásicas", ar: "المهام الكلاسيكية", de: "Klassik-Missionen", fr: "Missions classiques", he: "משימות קלאסיות", pt: "Missões clássicas", tr: "Klasik görevler").dict,
    "menu.classic.sub": Tr(zh: "240个关卡 · 逐步解锁", en: "240 levels · Unlock progressively", hant: "240 個關卡 · 逐步解鎖", ja: "240レベル · 順に解放", ko: "240개 레벨 · 순차 해제", es: "240 niveles · Desbloqueo progresivo", ar: "240 مستوى · فتح تدريجي", de: "240 Level · Schrittweise frei", fr: "240 niveaux · Déblocage progressif", he: "240 שלבים · נפתחים בהדרגה", pt: "240 níveis · Desbloqueio progressivo", tr: "240 seviye · Sırayla açılır").dict,
    "menu.lie": Tr(zh: "谎言任务", en: "Lie Missions", hant: "謊言任務", ja: "嘘の任務", ko: "거짓말 임무", es: "Misiones Mentira", ar: "مهام الكذب", de: "Lügen-Missionen", fr: "Missions Mensonge", he: "משימות שקר", pt: "Missões Mentira", tr: "Yalan görevleri").dict,
    "menu.lie.sub": Tr(zh: "前80关免费 · 含1次虚假反馈", en: "80 free · 1 fake feedback", hant: "前 80 關免費 · 含 1 次虛假回饋", ja: "最初の80は無料 · 嘘の手がかり1回", ko: "처음 80개 무료 · 가짜 단서 1회", es: "80 gratis · 1 pista falsa", ar: "80 مجانًا · دليل مزيف واحد", de: "80 gratis · 1 falscher Hinweis", fr: "80 gratuits · 1 indice faux", he: "80 בחינם · רמז מזויף אחד", pt: "80 grátis · 1 pista falsa", tr: "80 ücretsiz · 1 sahte ipucu").dict,
    "menu.free": Tr(zh: "自由模式", en: "Free Play", hant: "自由模式", ja: "フリープレイ", ko: "자유 플레이", es: "Juego libre", ar: "لعب حر", de: "Freies Spiel", fr: "Partie libre", he: "משחק חופשי", pt: "Jogo livre", tr: "Serbest oyun").dict,
    "menu.free.sub": Tr(zh: "自定义难度 · 无限挑战", en: "Custom difficulty · Endless", hant: "自訂難度 · 無限挑戰", ja: "難易度自由 · 回数無制限", ko: "난이도 맞춤 · 무한 도전", es: "Dificultad a medida · Sin fin", ar: "صعوبة مخصصة · بلا نهاية", de: "Eigene Schwierigkeit · Endlos", fr: "Difficulté libre · Sans fin", he: "קושי מותאם · בלי סוף", pt: "Dificuldade livre · Sem fim", tr: "Özel zorluk · Sonsuz").dict,
    "menu.duel": Tr(zh: "双人对战", en: "Duel Mode", hant: "雙人對戰", ja: "対戦モード", ko: "대전 모드", es: "Modo duelo", ar: "وضع المبارزة", de: "Duellmodus", fr: "Mode duel", he: "מצב דו-קרב", pt: "Modo duelo", tr: "Düello modu").dict,
    "menu.duel.sub": Tr(zh: "一人设密码 · 一人来破译", en: "One sets · One cracks", hant: "一人設密碼 · 一人來破譯", ja: "一人が設定 · 一人が解読", ko: "한 명이 설정 · 한 명이 해독", es: "Uno pone · Otro descifra", ar: "واحد يضع · واحد يفك", de: "Einer legt · Einer knackt", fr: "L’un pose · L’autre casse", he: "אחד קובע · אחד מפצח", pt: "Um define · Outro decifra", tr: "Biri koyar · Biri çözer").dict,
    "menu.editor": Tr(zh: "自定义关卡", en: "Custom Level", hant: "自訂關卡", ja: "カスタムレベル", ko: "커스텀 레벨", es: "Nivel personalizado", ar: "مستوى مخصص", de: "Eigenes Level", fr: "Niveau perso", he: "שלב מותאם", pt: "Nível personalizado", tr: "Özel seviye").dict,
    "menu.editor.sub": Tr(zh: "调整所有参数 · 创造挑战", en: "All params · Create challenge", hant: "調整所有參數 · 創造挑戰", ja: "全パラメータ調整 · 問題を作る", ko: "모든 파라미터 · 도전 만들기", es: "Todos los parámetros · Crea un reto", ar: "كل الإعدادات · اصنع تحديًا", de: "Alle Parameter · Challenge bauen", fr: "Tous les paramètres · Crée un défi", he: "כל הפרמטרים · צור אתגר", pt: "Todos os parâmetros · Crie um desafio", tr: "Tüm ayarlar · Görev oluştur").dict,
    "menu.more": Tr(zh: "更多", en: "More", hant: "更多", ja: "その他", ko: "더보기", es: "Más", ar: "المزيد", de: "Mehr", fr: "Plus", he: "עוד", pt: "Mais", tr: "Daha fazla").dict,
    "menu.classic.short": Tr(zh: "240 关逐步解锁", en: "240 levels", hant: "240 關逐步解鎖", ja: "240レベル", ko: "240개 레벨", es: "240 niveles", ar: "240 مستوى", de: "240 Level", fr: "240 niveaux", he: "240 שלבים", pt: "240 níveis", tr: "240 seviye").dict,
    "menu.lie.short": Tr(zh: "一条线索是假的", en: "One clue is fake", hant: "一條線索是假的", ja: "手がかりの1つは嘘", ko: "단서 하나가 가짜", es: "Una pista es falsa", ar: "دليل واحد مزيف", de: "Ein Hinweis ist falsch", fr: "Un indice est faux", he: "רמז אחד מזויף", pt: "Uma pista é falsa", tr: "Bir ipucu yalan").dict,
    "menu.achievements": Tr(zh: "成就", en: "Achievements", hant: "成就", ja: "実績", ko: "업적", es: "Logros", ar: "الإنجازات", de: "Erfolge", fr: "Succès", he: "הישגים", pt: "Conquistas", tr: "Başarımlar").dict,
    "menu.feedback": Tr(zh: "发送反馈", en: "Send Feedback", hant: "傳送回饋", ja: "フィードバック", ko: "의견 보내기", es: "Enviar comentarios", ar: "إرسال ملاحظات", de: "Feedback senden", fr: "Envoyer un avis", he: "שלח משוב", pt: "Enviar comentário", tr: "Geri bildirim gönder").dict,
    "menu.feedback.sub": Tr(zh: "认真反馈可送 Pro", en: "Useful feedback may unlock Pro", hant: "認真回饋可送 Pro", ja: "有用な指摘でProを贈呈することも", ko: "유용한 의견이면 Pro를 드릴 수 있어요", es: "Un comentario útil puede desbloquear Pro", ar: "ملاحظة مفيدة قد تفتح Pro", de: "Nützliches Feedback kann Pro freischalten", fr: "Un avis utile peut débloquer Pro", he: "משוב מועיל עשוי לפתוח Pro", pt: "Um comentário útil pode liberar Pro", tr: "Faydalı geri bildirim Pro açabilir").dict,
    "home.feedback.tip": Tr(zh: "有用的反馈可送 Pro", en: "Useful feedback can unlock Pro", hant: "有用的回饋可送 Pro", ja: "役立つ指摘でProを贈呈", ko: "유용한 의견이면 Pro 증정", es: "Un comentario útil puede darte Pro", ar: "ملاحظة مفيدة قد تهدي Pro", de: "Nützliches Feedback kann Pro schenken", fr: "Un avis utile peut offrir Pro", he: "משוב מועיל יכול להעניק Pro", pt: "Um comentário útil pode dar Pro", tr: "Faydalı geri bildirim Pro hediye edebilir").dict,
    "stats.games": Tr(zh: "总局数", en: "Games", hant: "總局數", ja: "プレイ数", ko: "판수", es: "Partidas", ar: "جولات", de: "Spiele", fr: "Parties", he: "משחקים", pt: "Partidas", tr: "Oyun").dict,
    "stats.winrate": Tr(zh: "胜率", en: "Win%", hant: "勝率", ja: "勝率", ko: "승률", es: "% victorias", ar: "فوز%", de: "Sieg%", fr: "% victoires", he: "% ניצחון", pt: "% vitórias", tr: "Galibiyet%").dict,
    "stats.streak": Tr(zh: "连胜", en: "Streak", hant: "連勝", ja: "連勝", ko: "연승", es: "Racha", ar: "سلسلة", de: "Serie", fr: "Série", he: "רצף", pt: "Sequência", tr: "Seri").dict,
    "stats.stars": Tr(zh: "星数", en: "Stars", hant: "星數", ja: "星", ko: "별", es: "Estrellas", ar: "نجوم", de: "Sterne", fr: "Étoiles", he: "כוכבים", pt: "Estrelas", tr: "Yıldız").dict,
    "stats.best": Tr(zh: "最佳", en: "Best", hant: "最佳", ja: "最高", ko: "최고", es: "Mejor", ar: "أفضل", de: "Beste", fr: "Meilleur", he: "שיא", pt: "Melhor", tr: "En iyi").dict,
    "game.free": Tr(zh: "自由模式", en: "Free Play", hant: "自由模式", ja: "フリープレイ", ko: "자유 플레이", es: "Juego libre", ar: "لعب حر", de: "Freies Spiel", fr: "Partie libre", he: "משחק חופשי", pt: "Jogo livre", tr: "Serbest oyun").dict,
    "game.start": Tr(zh: "开始挑战", en: "Start Challenge", hant: "開始挑戰", ja: "挑戦を始める", ko: "도전 시작", es: "Empezar reto", ar: "ابدأ التحدي", de: "Herausforderung starten", fr: "Lancer le défi", he: "התחל אתגר", pt: "Começar desafio", tr: "Göreve başla").dict,
    "game.duel": Tr(zh: "双人对战", en: "Duel Mode", hant: "雙人對戰", ja: "対戦モード", ko: "대전 모드", es: "Modo duelo", ar: "وضع المبارزة", de: "Duellmodus", fr: "Mode duel", he: "מצב דו-קרב", pt: "Modo duelo", tr: "Düello modu").dict,
    "game.attempts": Tr(zh: "次", en: "left", hant: "次", ja: "残", ko: "남음", es: "restan", ar: "متبقٍ", de: "übrig", fr: "restants", he: "נותרו", pt: "restam", tr: "kaldı").dict,
    "game.hint": Tr(zh: "提示", en: "Hint", hant: "提示", ja: "ヒント", ko: "힌트", es: "Pista", ar: "تلميح", de: "Tipp", fr: "Indice", he: "רמז", pt: "Dica", tr: "İpucu").dict,
    "game.submit": Tr(zh: "提交", en: "Submit", hant: "提交", ja: "送信", ko: "제출", es: "Enviar", ar: "إرسال", de: "Senden", fr: "Valider", he: "שלח", pt: "Enviar", tr: "Gönder").dict,
    "param.length": Tr(zh: "密码长度", en: "Code length", hant: "密碼長度", ja: "コードの長さ", ko: "암호 길이", es: "Longitud", ar: "طول الرمز", de: "Codelänge", fr: "Longueur", he: "אורך הקוד", pt: "Comprimento", tr: "Kod uzunluğu").dict,
    "param.colors": Tr(zh: "可用颜色", en: "Colors", hant: "可用顏色", ja: "色数", ko: "색 수", es: "Colores", ar: "الألوان", de: "Farben", fr: "Couleurs", he: "צבעים", pt: "Cores", tr: "Renkler").dict,
    "param.attempts": Tr(zh: "最大尝试", en: "Max attempts", hant: "最大嘗試", ja: "最大手数", ko: "최대 시도", es: "Intentos máx.", ar: "أقصى محاولات", de: "Max. Versuche", fr: "Essais max.", he: "מקס׳ ניסיונות", pt: "Tentativas máx.", tr: "Maks. deneme").dict,
    "param.repeat": Tr(zh: "允许重复", en: "Allow repeats", hant: "允許重複", ja: "重複を許可", ko: "중복 허용", es: "Permitir repeticiones", ar: "السماح بالتكرار", de: "Wiederholungen", fr: "Autoriser les doublons", he: "לאפשר כפילויות", pt: "Permitir repetições", tr: "Tekrara izin").dict,
    "param.timelimit": Tr(zh: "时间限制", en: "Time limit", hant: "時間限制", ja: "制限時間", ko: "시간 제한", es: "Límite de tiempo", ar: "حد زمني", de: "Zeitlimit", fr: "Limite de temps", he: "מגבלת זמן", pt: "Limite de tempo", tr: "Süre sınırı").dict,
    "param.yes": Tr(zh: "是", en: "Yes", hant: "是", ja: "あり", ko: "예", es: "Sí", ar: "نعم", de: "Ja", fr: "Oui", he: "כן", pt: "Sim", tr: "Evet").dict,
    "param.no": Tr(zh: "否", en: "No", hant: "否", ja: "なし", ko: "아니요", es: "No", ar: "لا", de: "Nein", fr: "Non", he: "לא", pt: "Não", tr: "Hayır").dict,
    "result.win": Tr(zh: "密码破译成功！", en: "Code Cracked!", hant: "密碼破譯成功！", ja: "解読成功！", ko: "암호 해독 성공!", es: "¡Código descifrado!", ar: "فُك الرمز!", de: "Code geknackt!", fr: "Code cassé !", he: "הקוד פוצח!", pt: "Código decifrado!", tr: "Kod kırıldı!").dict,
    "result.win.steps": Tr(zh: "用了 %d 步完成破译", en: "Solved in %d steps", hant: "用了 %d 步完成破譯", ja: "%d手で解読", ko: "%d수 만에 해독", es: "Resuelto en %d pasos", ar: "حُلّ في %d خطوة", de: "In %d Zügen gelöst", fr: "Résolu en %d coups", he: "נפתר ב־%d מהלכים", pt: "Resolvido em %d passos", tr: "%d hamlede çözüldü").dict,
    "result.lose": Tr(zh: "破译失败", en: "Failed", hant: "破譯失敗", ja: "解読失敗", ko: "해독 실패", es: "Fallaste", ar: "فشل", de: "Gescheitert", fr: "Échec", he: "נכשל", pt: "Falhou", tr: "Başarısız").dict,
    "result.lose.desc": Tr(zh: "密码未能在限定次数内破解", en: "Code not cracked within the limit", hant: "密碼未能在限定次數內破解", ja: "制限手数内に解読できなかった", ko: "제한 횟수 안에 해독하지 못함", es: "No descifraste el código a tiempo", ar: "لم يُفك الرمز ضمن الحد", de: "Code nicht rechtzeitig geknackt", fr: "Code non cassé dans la limite", he: "הקוד לא פוצח בזמן", pt: "Código não decifrado a tempo", tr: "Kod süre içinde kırılmadı").dict,
    "result.code": Tr(zh: "密码：", en: "Code:", hant: "密碼：", ja: "コード：", ko: "암호:", es: "Código:", ar: "الرمز:", de: "Code:", fr: "Code :", he: "קוד:", pt: "Código:", tr: "Kod:").dict,
    "result.retry": Tr(zh: "重新挑战", en: "Retry", hant: "重新挑戰", ja: "再挑戦", ko: "다시 도전", es: "Reintentar", ar: "إعادة", de: "Nochmal", fr: "Réessayer", he: "נסה שוב", pt: "Tentar de novo", tr: "Tekrar dene").dict,
    "result.next": Tr(zh: "下一关 →", en: "Next →", hant: "下一關 →", ja: "次へ →", ko: "다음 →", es: "Siguiente →", ar: "التالي ←", de: "Weiter →", fr: "Suivant →", he: "הבא ←", pt: "Seguinte →", tr: "İleri →").dict,
    "result.again": Tr(zh: "再来一局", en: "Play Again", hant: "再來一局", ja: "もう一局", ko: "한 판 더", es: "Jugar de nuevo", ar: "جولة أخرى", de: "Nochmal spielen", fr: "Rejouer", he: "משחק נוסף", pt: "Jogar de novo", tr: "Bir tur daha").dict,
    "result.share": Tr(zh: "分享", en: "Share", hant: "分享", ja: "シェア", ko: "공유", es: "Compartir", ar: "مشاركة", de: "Teilen", fr: "Partager", he: "שתף", pt: "Compartilhar", tr: "Paylaş").dict,
    "result.back": Tr(zh: "返回", en: "Back", hant: "返回", ja: "戻る", ko: "뒤로", es: "Volver", ar: "رجوع", de: "Zurück", fr: "Retour", he: "חזרה", pt: "Voltar", tr: "Geri").dict,
    "lie.mode": Tr(zh: "谎言模式", en: "Lie Mode", hant: "謊言模式", ja: "嘘モード", ko: "거짓말 모드", es: "Modo Mentira", ar: "وضع الكذب", de: "Lügenmodus", fr: "Mode Mensonge", he: "מצב שקר", pt: "Modo Mentira", tr: "Yalan modu").dict,
    "lie.warning": Tr(zh: "谎言模式", en: "Lie Mode", hant: "謊言模式", ja: "嘘モード", ko: "거짓말 모드", es: "Modo Mentira", ar: "وضع الكذب", de: "Lügenmodus", fr: "Mode Mensonge", he: "מצב שקר", pt: "Modo Mentira", tr: "Yalan modu").dict,
    "lie.task": Tr(zh: "谎言任务", en: "Lie Missions", hant: "謊言任務", ja: "嘘の任務", ko: "거짓말 임무", es: "Misiones Mentira", ar: "مهام الكذب", de: "Lügen-Missionen", fr: "Missions Mensonge", he: "משימות שקר", pt: "Missões Mentira", tr: "Yalan görevleri").dict,
    "lie.banner": Tr(zh: "每关含1次虚假反馈", en: "1 fake feedback per level", hant: "每關含 1 次虛假回饋", ja: "各レベルで嘘の手がかり1回", ko: "레벨마다 가짜 단서 1회", es: "1 pista falsa por nivel", ar: "دليل مزيف واحد لكل مستوى", de: "1 falscher Hinweis pro Level", fr: "1 indice faux par niveau", he: "רמז מזויף אחד בכל שלב", pt: "1 pista falsa por nível", tr: "Seviye başına 1 sahte ipucu").dict,
    "lie.reveal": Tr(zh: "第 %d 步是谎言！", en: "Step %d was a lie!", hant: "第 %d 步是謊言！", ja: "%d手目が嘘だった！", ko: "%d번째 수가 거짓이었습니다!", es: "¡El paso %d era mentira!", ar: "الخطوة %d كانت كذبة!", de: "Zug %d war eine Lüge!", fr: "Le coup %d était un mensonge !", he: "מהלך %d היה שקר!", pt: "O passo %d era mentira!", tr: "%d. hamle yalandı!").dict,
    "lie.fake": Tr(zh: "当时显示", en: "Shown", hant: "當時顯示", ja: "当時の表示", ko: "그때 표시", es: "Mostrado", ar: "المعروض", de: "Gezeigt", fr: "Affiché", he: "הוצג", pt: "Mostrado", tr: "Gösterilen").dict,
    "lie.real": Tr(zh: "→ 实际是", en: "→ Truth", hant: "→ 實際是", ja: "→ 本当は", ko: "→ 실제", es: "→ Verdad", ar: "← الحقيقة", de: "→ Wahrheit", fr: "→ Vérité", he: "← האמת", pt: "→ Verdade", tr: "→ Gerçek").dict,
    "lie.real.short": Tr(zh: "实际是", en: "Truth", hant: "實際是", ja: "本当は", ko: "실제", es: "Verdad", ar: "الحقيقة", de: "Wahrheit", fr: "Vérité", he: "אמת", pt: "Verdade", tr: "Gerçek").dict,
    "lie.feedback": Tr(zh: "%d精确 %d位置", en: "%d exact %d partial", hant: "%d 精確 %d 位置", ja: "正確%d 位置違い%d", ko: "정확 %d 위치만 %d", es: "%d exactos %d parciales", ar: "%d دقيق %d جزئي", de: "%d exakt %d teilweise", fr: "%d exacts %d partiels", he: "%d מדויק %d חלקי", pt: "%d exatos %d parciais", tr: "%d tam %d kısmi").dict,
    "lie.notrigger": Tr(zh: "本局谎言未触发（你赢得太快了！）", en: "No lie triggered (you won too fast!)", hant: "本局謊言未觸發（你贏得太快了！）", ja: "嘘は出なかった（勝ちが早すぎた！）", ko: "거짓이 나오지 않음 (너무 빨리 이김!)", es: "No hubo mentira (¡ganaste muy rápido!)", ar: "لم يظهر كذب (فزت بسرعة!)", de: "Keine Lüge (zu schnell gewonnen!)", fr: "Pas de mensonge (victoire trop rapide !)", he: "לא היה שקר (ניצחת מהר מדי!)", pt: "Sem mentira (você ganhou rápido demais!)", tr: "Yalan çıkmadı (çok çabuk kazandın!)").dict,
    "lie.start": Tr(zh: "开始谎言挑战", en: "Start Lie Challenge", hant: "開始謊言挑戰", ja: "嘘モードを始める", ko: "거짓말 도전 시작", es: "Empezar Mentira", ar: "ابدأ تحدي الكذب", de: "Lügen-Challenge starten", fr: "Lancer le Mensonge", he: "התחל אתגר שקר", pt: "Começar Mentira", tr: "Yalan görevine başla").dict,
    "lie.toggle": Tr(zh: "谎言模式", en: "Lie Mode", hant: "謊言模式", ja: "嘘モード", ko: "거짓말 모드", es: "Modo Mentira", ar: "وضع الكذب", de: "Lügenmodus", fr: "Mode Mensonge", he: "מצב שקר", pt: "Modo Mentira", tr: "Yalan modu").dict,
    "lie.toggle.desc": Tr(zh: "含1次虚假反馈", en: "Includes 1 fake feedback", hant: "含 1 次虛假回饋", ja: "嘘の手がかり1回", ko: "가짜 단서 1회 포함", es: "Incluye 1 pista falsa", ar: "يتضمن دليلًا مزيفًا واحدًا", de: "Enthält 1 falschen Hinweis", fr: "Inclut 1 indice faux", he: "כולל רמז מזויף אחד", pt: "Inclui 1 pista falsa", tr: "1 sahte ipucu içerir").dict,
    "lie.kickoff": Tr(zh: "这一局里，有一条线索会说谎", en: "One of these clues will lie", hant: "這一局裡，有一條線索會說謊", ja: "このラウンド、手がかりの1つが嘘をつく", ko: "이번 판에서 단서 하나가 거짓입니다", es: "En esta ronda, una pista mentirá", ar: "في هذه الجولة، دليل واحد سيكذب", de: "Einer dieser Hinweise wird lügen", fr: "Un de ces indices va mentir", he: "ברמה הזו, רמז אחד ישקר", pt: "Nesta rodada, uma pista mentirá", tr: "Bu turda bir ipucu yalan söyleyecek").dict,
    "lie.clue": Tr(zh: "其中一条线索是假的", en: "One of these clues is false", hant: "其中一條線索是假的", ja: "手がかりの1つは嘘", ko: "단서 중 하나가 가짜입니다", es: "Una de estas pistas es falsa", ar: "أحد هذه الأدلة مزيف", de: "Einer dieser Hinweise ist falsch", fr: "Un de ces indices est faux", he: "אחד הרמזים האלה מזויף", pt: "Uma destas pistas é falsa", tr: "Bu ipuçlarından biri yalan").dict,
    "lie.stamp": Tr(zh: "谎", en: "LIE", hant: "謊", ja: "嘘", ko: "거짓", es: "FALSO", ar: "كذب", de: "LÜGE", fr: "FAUX", he: "שקר", pt: "FALSO", tr: "YALAN").dict,
    "level.title": Tr(zh: "关卡 %d", en: "Level %d", hant: "關卡 %d", ja: "レベル %d", ko: "레벨 %d", es: "Nivel %d", ar: "المستوى %d", de: "Level %d", fr: "Niveau %d", he: "שלב %d", pt: "Nível %d", tr: "Seviye %d").dict,
    "level.tier1": Tr(zh: "初级特工", en: "Junior Agent", hant: "初級特工", ja: "見習いエージェント", ko: "초급 요원", es: "Agente junior", ar: "عميل مبتدئ", de: "Junior-Agent", fr: "Agent junior", he: "סוכן זוטר", pt: "Agente júnior", tr: "Çaylak ajan").dict,
    "level.tier2": Tr(zh: "中级特工", en: "Agent", hant: "中級特工", ja: "エージェント", ko: "요원", es: "Agente", ar: "عميل", de: "Agent", fr: "Agent", he: "סוכן", pt: "Agente", tr: "Ajan").dict,
    "level.tier3": Tr(zh: "高级特工", en: "Senior Agent", hant: "高級特工", ja: "上級エージェント", ko: "상급 요원", es: "Agente senior", ar: "عميل أول", de: "Senior-Agent", fr: "Agent senior", he: "סוכן בכיר", pt: "Agente sênior", tr: "Kıdemli ajan").dict,
    "level.tier4": Tr(zh: "精英特工", en: "Elite Agent", hant: "精英特工", ja: "エリート", ko: "엘리트 요원", es: "Agente de élite", ar: "عميل نخبة", de: "Elite-Agent", fr: "Agent d’élite", he: "סוכן עלית", pt: "Agente de elite", tr: "Elit ajan").dict,
    "level.tier5": Tr(zh: "首席特工", en: "Chief Agent", hant: "首席特工", ja: "チーフ", ko: "수석 요원", es: "Agente jefe", ar: "العميل الرئيسي", de: "Chef-Agent", fr: "Agent en chef", he: "סוכן ראשי", pt: "Agente-chefe", tr: "Baş ajan").dict,
    "level.tier6": Tr(zh: "传奇特工", en: "Legend Agent", hant: "傳奇特工", ja: "レジェンド", ko: "전설 요원", es: "Agente leyenda", ar: "عميل أسطوري", de: "Legenden-Agent", fr: "Agent légende", he: "סוכן אגדה", pt: "Agente lenda", tr: "Efsane ajan").dict,
    "tutorial.next": Tr(zh: "下一步", en: "Next", hant: "下一步", ja: "次へ", ko: "다음", es: "Siguiente", ar: "التالي", de: "Weiter", fr: "Suivant", he: "הבא", pt: "Seguinte", tr: "İleri").dict,
    "tutorial.start": Tr(zh: "开始破译！", en: "Start Cracking!", hant: "開始破譯！", ja: "解読開始！", ko: "해독 시작!", es: "¡A descifrar!", ar: "ابدأ الفك!", de: "Los knacken!", fr: "À casser !", he: "התחל לפצח!", pt: "Decifrar!", tr: "Kırmaya başla!").dict,
    "tutorial.t1": Tr(zh: "破译隐藏密码", en: "Crack the Code", hant: "破譯隱藏密碼", ja: "隠しコードを解読せよ", ko: "숨겨진 암호를 풀어라", es: "Descifra el código", ar: "فك الرمز المخفي", de: "Knacke den Code", fr: "Casse le code", he: "פצח את הקוד", pt: "Decifre o código", tr: "Kodu kır").dict,
    "tutorial.t2": Tr(zh: "选择颜色填入", en: "Pick Colors", hant: "選擇顏色填入", ja: "色を選んで入れる", ko: "색을 골라 넣기", es: "Elige colores", ar: "اختر الألوان", de: "Farben wählen", fr: "Choisis des couleurs", he: "בחר צבעים", pt: "Escolha cores", tr: "Renk seç").dict,
    "tutorial.t3": Tr(zh: "解读反馈线索", en: "Read the Clues", hant: "解讀回饋線索", ja: "手がかりを読む", ko: "단서 읽기", es: "Lee las pistas", ar: "اقرأ الأدلة", de: "Hinweise lesen", fr: "Lis les indices", he: "קרא את הרמזים", pt: "Leia as pistas", tr: "İpuçlarını oku").dict,
    "tutorial.t4": Tr(zh: "善用提示", en: "Use Hints", hant: "善用提示", ja: "ヒントを使う", ko: "힌트 활용", es: "Usa pistas", ar: "استخدم التلميحات", de: "Tipps nutzen", fr: "Utilise les indices", he: "השתמש ברמזים", pt: "Use dicas", tr: "İpucu kullan").dict,
    "tutorial.d1": Tr(zh: "系统生成了一组隐藏的颜色密码\n你需要在有限次数内猜出正确组合", en: "A secret color code is hidden\nGuess it within limited attempts", hant: "系統生成了一組隱藏的顏色密碼\n你需要在有限次數內猜出正確組合", ja: "隠された色のコードがある\n制限手数の中で当てよう", ko: "숨겨진 색 암호가 있습니다\n제한된 횟수 안에 맞추세요", es: "Hay un código de colores oculto\nAdivínalo con intentos limitados", ar: "رمز ألوان سري مخفي\nخمّنه ضمن محاولات محدودة", de: "Ein geheimer Farbcode ist versteckt\nRate ihn in begrenzten Versuchen", fr: "Un code couleur secret est caché\nTrouve-le avec peu d’essais", he: "קוד צבעים סודי מוסתר\nנחש אותו במספר ניסיונות מוגבל", pt: "Há um código de cores secreto\nAdivinhe com tentativas limitadas", tr: "Gizli bir renk kodu var\nSınırlı denemede tahmin et").dict,
    "tutorial.d2": Tr(zh: "点击底部颜色球放入猜测槽位\n填满所有位置后点击提交", en: "Tap colors to fill slots\nSubmit when all slots are filled", hant: "點擊底部顏色球放入猜測槽位\n填滿所有位置後點擊提交", ja: "下の色をタップしてスロットへ\n埋まったら送信", ko: "아래 색을 눌러 칸에 넣으세요\n다 채우면 제출", es: "Toca colores para llenar huecos\nEnvía cuando estén todos", ar: "اضغط الألوان لملء الخانات\nعند الامتلاء اضغط إرسال", de: "Tippe Farben in die Slots\nSenden, wenn alle voll sind", fr: "Touche les couleurs pour remplir\nValide quand tout est plein", he: "הקש על צבעים למילוי המשבצות\nשלח כשהכול מלא", pt: "Toque cores para preencher\nEnvie quando estiver completo", tr: "Renklere dokunup yuvaları doldur\nHepsi dolunca gönder").dict,
    "tutorial.d3": Tr(zh: "青圆 = 颜色和位置都对\n橙三角 = 颜色对但位置不对\n黑叉 = 该颜色不在密码中", en: "Teal circle = Right color, right spot\nOrange triangle = Right color, wrong spot\nBlack cross = Not in the code", hant: "青圓 = 顏色和位置都對\n橙三角 = 顏色對但位置不對\n黑叉 = 該顏色不在密碼中", ja: "青緑の丸 = 色も位置も正しい\nオレンジの三角 = 色は正しいが位置が違う\n黒いバツ = その色はコードにない", ko: "청록 원 = 색과 위치 모두 맞음\n주황 삼각형 = 색은 맞지만 위치가 다름\n검은 엑스 = 암호에 없는 색", es: "Círculo teal = Color y posición correctos\nTriángulo naranja = Color bien, sitio mal\nCruz negra = Ese color no está", ar: "دائرة فيروزية = اللون والمكان صحيحان\nمثلث برتقالي = اللون صحيح والمكان خطأ\nعلامة سوداء = اللون ليس في الرمز", de: "Türkis-Kreis = Farbe und Platz richtig\nOranges Dreieck = Farbe richtig, Platz falsch\nSchwarzes Kreuz = Nicht im Code", fr: "Cercle teal = Bonne couleur, bon emplacement\nTriangle orange = Bonne couleur, mauvais endroit\nCroix noire = Pas dans le code", he: "עיגול טורקיז = צבע ומיקום נכונים\nמשולש כתום = צבע נכון, מיקום שגוי\nאיקס שחור = הצבע לא בקוד", pt: "Círculo teal = Cor e posição certas\nTriângulo laranja = Cor certa, lugar errado\nCruz preta = Cor não está no código", tr: "Turkuaz daire = Renk ve yer doğru\nTuruncu üçgen = Renk doğru, yer yanlış\nSiyah çarpı = Bu renk kodda yok").dict,
    "tutorial.d4": Tr(zh: "每局有一次提示机会\n会告诉你某个位置的正确颜色", en: "One hint per game\nReveals the color at a position", hant: "每局有一次提示機會\n會告訴你某個位置的正確顏色", ja: "1プレイ1回のヒント\nある位置の正しい色がわかる", ko: "판마다 힌트 한 번\n한 칸의 올바른 색을 알려 줍니다", es: "Una pista por partida\nRevela el color de una posición", ar: "تلميح واحد لكل جولة\nيكشف لون موضع معيّن", de: "Ein Tipp pro Spiel\nZeigt die Farbe an einer Position", fr: "Un indice par partie\nRévèle la couleur d’une position", he: "רמז אחד למשחק\nחושף את הצבע בעמדה", pt: "Uma dica por partida\nRevela a cor de uma posição", tr: "Tur başına bir ipucu\nBir konumun rengini gösterir").dict,
    "duel.title": Tr(zh: "双人对战", en: "Duel Mode", hant: "雙人對戰", ja: "対戦モード", ko: "대전 모드", es: "Modo duelo", ar: "وضع المبارزة", de: "Duellmodus", fr: "Mode duel", he: "מצב דו-קרב", pt: "Modo duelo", tr: "Düello modu").dict,
    "duel.desc": Tr(zh: "一人设密码，一人来破译", en: "One sets code, one cracks it", hant: "一人設密碼，一人來破譯", ja: "一人がコードを設定し、もう一人が解読", ko: "한 명이 암호를 정하고, 한 명이 풉니다", es: "Uno pone el código, el otro lo descifra", ar: "واحد يضع الرمز، والآخر يفكه", de: "Einer legt den Code, einer knackt ihn", fr: "L’un pose le code, l’autre le casse", he: "אחד קובע קוד, השני מפצח", pt: "Um define o código, o outro decifra", tr: "Biri kodu koyar, diğeri çözer").dict,
    "duel.p1.setup": Tr(zh: "玩家 1 设置密码", en: "Player 1: Set Code", hant: "玩家 1 設定密碼", ja: "プレイヤー1：コードを設定", ko: "플레이어 1: 암호 설정", es: "Jugador 1: poner código", ar: "اللاعب 1: ضع الرمز", de: "Spieler 1: Code legen", fr: "Joueur 1 : poser le code", he: "שחקן 1: קבע קוד", pt: "Jogador 1: definir código", tr: "Oyuncu 1: kodu koy").dict,
    "duel.p2.start": Tr(zh: "玩家 2 开始破译", en: "Player 2: Start", hant: "玩家 2 開始破譯", ja: "プレイヤー2：解読開始", ko: "플레이어 2: 시작", es: "Jugador 2: empezar", ar: "اللاعب 2: ابدأ", de: "Spieler 2: Start", fr: "Joueur 2 : commencer", he: "שחקן 2: התחל", pt: "Jogador 2: começar", tr: "Oyuncu 2: başla").dict,
    "duel.confirm": Tr(zh: "密码已设好 →", en: "Code Set →", hant: "密碼已設好 →", ja: "コード設定完了 →", ko: "암호 설정됨 →", es: "Código listo →", ar: "الرمز جاهز ←", de: "Code gesetzt →", fr: "Code prêt →", he: "הקוד נקבע ←", pt: "Código pronto →", tr: "Kod hazır →").dict,
    "duel.handoff": Tr(zh: "请将手机交给对手", en: "Pass to Opponent", hant: "請將手機交給對手", ja: "相手に渡して", ko: "상대에게 넘기세요", es: "Pásaselo al rival", ar: "مرّر الهاتف للخصم", de: "Ans Gegenüber geben", fr: "Passe au rival", he: "העבר ליריב", pt: "Passe ao rival", tr: "Telefona rakibe ver").dict,
    "duel.handoff.desc": Tr(zh: "密码已锁定，请勿偷看！", en: "Code locked. No peeking!", hant: "密碼已鎖定，請勿偷看！", ja: "コードはロック済み。覗き見禁止！", ko: "암호가 잠겼습니다. 훔쳐보지 마세요!", es: "Código bloqueado. ¡Sin mirar!", ar: "الرمز مقفل. لا تختلس النظر!", de: "Code gesperrt. Nicht spicken!", fr: "Code verrouillé. Pas de coup d’œil !", he: "הקוד נעול. בלי להציץ!", pt: "Código travado. Sem espiar!", tr: "Kod kilitli. Bakmak yok!").dict,
    "duel.rules": Tr(zh: "对战规则", en: "Rules", hant: "對戰規則", ja: "ルール", ko: "규칙", es: "Reglas", ar: "القواعد", de: "Regeln", fr: "Règles", he: "כללים", pt: "Regras", tr: "Kurallar").dict,
    "settings.title": Tr(zh: "设置", en: "Settings", hant: "設定", ja: "設定", ko: "설정", es: "Ajustes", ar: "الإعدادات", de: "Einstellungen", fr: "Réglages", he: "הגדרות", pt: "Ajustes", tr: "Ayarlar").dict,
    "settings.sound": Tr(zh: "音效", en: "Sound", hant: "音效", ja: "効果音", ko: "효과음", es: "Sonido", ar: "الصوت", de: "Ton", fr: "Son", he: "צליל", pt: "Som", tr: "Ses").dict,
    "settings.haptics": Tr(zh: "触觉反馈", en: "Haptics", hant: "觸覺回饋", ja: "触覚", ko: "햅틱", es: "Hápticos", ar: "الاهتزاز", de: "Haptik", fr: "Haptique", he: "רטט", pt: "Hápticos", tr: "Titreşim").dict,
    "settings.colorblind": Tr(zh: "色盲辅助", en: "Colorblind", hant: "色盲輔助", ja: "色覚サポート", ko: "색각 보조", es: "Daltonismo", ar: "مساعدة عمى الألوان", de: "Farbenblind", fr: "Daltonisme", he: "עיוורון צבעים", pt: "Daltonismo", tr: "Renk körlüğü").dict,
    "feedback.section": Tr(zh: "支持", en: "Support", hant: "支援", ja: "サポート", ko: "지원", es: "Soporte", ar: "الدعم", de: "Support", fr: "Assistance", he: "תמיכה", pt: "Suporte", tr: "Destek").dict,
    "feedback.row": Tr(zh: "发送反馈", en: "Send Feedback", hant: "傳送回饋", ja: "フィードバックを送る", ko: "의견 보내기", es: "Enviar comentarios", ar: "إرسال ملاحظات", de: "Feedback senden", fr: "Envoyer un avis", he: "שלח משוב", pt: "Enviar comentário", tr: "Geri bildirim gönder").dict,
    "feedback.title": Tr(zh: "反馈", en: "Feedback", hant: "回饋", ja: "フィードバック", ko: "의견", es: "Comentarios", ar: "ملاحظات", de: "Feedback", fr: "Avis", he: "משוב", pt: "Comentários", tr: "Geri bildirim").dict,
    "feedback.lead": Tr(zh: "Bug、卡点和点子都欢迎。没有 GitHub 账号可以用 Google 或 Apple 登录。", en: "Bugs, rough edges, and ideas all help. You can sign in to GitHub with Google or Apple.", hant: "Bug、卡點和點子都歡迎。沒有 GitHub 帳號可以用 Google 或 Apple 登入。", ja: "バグ、引っかかり、アイデア歓迎。GitHubがなくてもGoogleやAppleでログインできます。", ko: "버그, 막히는 점, 아이디어 모두 환영합니다. GitHub 없이도 Google이나 Apple로 로그인할 수 있어요.", es: "Bugs, fricciones e ideas ayudan. Puedes entrar a GitHub con Google o Apple.", ar: "الأخطاء والنواقص والأفكار كلها مفيدة. يمكن تسجيل الدخول إلى GitHub بـ Google أو Apple.", de: "Bugs, Kanten und Ideen helfen. Du kannst dich bei GitHub mit Google oder Apple anmelden.", fr: "Bugs, aspérités et idées aident. Tu peux te connecter à GitHub avec Google ou Apple.", he: "באגים, חיכוכים ורעיונות עוזרים. אפשר להיכנס ל‑GitHub עם Google או Apple.", pt: "Bugs, arestas e ideias ajudam. Dá para entrar no GitHub com Google ou Apple.", tr: "Hata, sürtünme ve fikirlerin hepsi işe yarar. GitHub’a Google veya Apple ile girebilirsin.").dict,
    "feedback.pro": Tr(zh: "具体、能动手改的反馈，我们看过之后可能会私下赠送 Pro 兑换码。兑换码不会发在公开 Issue 里。App Store 评分不参与、也没有奖励。", en: "Specific, useful feedback may receive a Pro offer code after we review it. Codes are sent privately — never on the public issue. App Store ratings are not required and are not rewarded.", hant: "具體、能動手改的回饋，我們看過之後可能會私下贈送 Pro 兌換碼。兌換碼不會發在公開 Issue 裡。App Store 評分不參與、也沒有獎勵。", ja: "具体的で直せる指摘は、確認後にProコードを非公開で贈ることがあります。公開Issueには出しません。App Storeの評価は不要で、報酬もありません。", ko: "구체적이고 고칠 수 있는 의견은 검토 후 Pro 코드를 비공개로 드릴 수 있습니다. 공개 이슈에는 올리지 않습니다. App Store 평점은 필요 없고 보상도 없습니다.", es: "Un comentario concreto y accionable puede recibir un código Pro en privado. Nunca en el issue público. Las valoraciones de App Store no cuentan ni se recompensan.", ar: "ملاحظة محددة وقابلة للتنفيذ قد تحصل على رمز Pro بعد المراجعة. تُرسل الرموز سرًا — لا في Issue العلني. تقييمات App Store غير مطلوبة ولا تُكافأ.", de: "Konkretes, umsetzbares Feedback kann nach Prüfung einen Pro-Code erhalten. Codes gehen privat — nie im öffentlichen Issue. App-Store-Bewertungen sind nicht nötig und werden nicht belohnt.", fr: "Un avis précis et actionnable peut recevoir un code Pro après relecture. Les codes partent en privé — jamais sur l’issue public. Les notes App Store ne sont ni exigées ni récompensées.", he: "משוב ספציפי ובר־תיקון עשוי לקבל קוד Pro אחרי בדיקה. הקודים נשלחים בפרטי — לא בגיליון הציבורי. דירוגי App Store לא נדרשים ולא מתוגמלים.", pt: "Um comentário concreto e acionável pode receber um código Pro depois da revisão. Os códigos vão no privado — nunca no issue público. Avaliações da App Store não são exigidas nem recompensadas.", tr: "Somut, düzeltilebilir geri bildirim incelemeden sonra gizli bir Pro kodu alabilir. Kodlar herkese açık Issue’da yayınlanmaz. App Store puanı gerekmez ve ödül yoktur.").dict,
    "feedback.public": Tr(zh: "GitHub Issue 是公开的，不要写不想公开的信息。", en: "GitHub issues are public. Don't include anything you want to keep private.", hant: "GitHub Issue 是公開的，不要寫不想公開的資訊。", ja: "GitHubのIssueは公開です。隠したい情報は書かないでください。", ko: "GitHub 이슈는 공개입니다. 비밀로 두고 싶은 내용은 적지 마세요.", es: "Los issues de GitHub son públicos. No pongas nada privado.", ar: "Issues في GitHub عامة. لا تكتب ما تريد إبقاؤه سرًا.", de: "GitHub-Issues sind öffentlich. Schreib nichts Privates.", fr: "Les issues GitHub sont publics. N’y mets rien de privé.", he: "Issues ב‑GitHub ציבוריים. אל תכתוב מה שתרצה לשמור בסוד.", pt: "Issues do GitHub são públicos. Não escreva o que quiser manter privado.", tr: "GitHub Issue’ları herkese açıktır. Gizli kalmasını istediğin şeyi yazma.").dict,
    "feedback.github": Tr(zh: "打开 GitHub Issue", en: "Open GitHub Issue", hant: "開啟 GitHub Issue", ja: "GitHub Issueを開く", ko: "GitHub 이슈 열기", es: "Abrir issue en GitHub", ar: "فتح GitHub Issue", de: "GitHub-Issue öffnen", fr: "Ouvrir un issue GitHub", he: "פתח GitHub Issue", pt: "Abrir issue no GitHub", tr: "GitHub Issue aç").dict,
    "feedback.github.sub": Tr(zh: "在浏览器中打开，可用 Google / Apple 登录", en: "Opens GitHub in the browser", hant: "在瀏覽器中開啟，可用 Google / Apple 登入", ja: "ブラウザでGitHubを開きます", ko: "브라우저에서 GitHub를 엽니다", es: "Abre GitHub en el navegador", ar: "يفتح GitHub في المتصفح", de: "Öffnet GitHub im Browser", fr: "Ouvre GitHub dans le navigateur", he: "פותח את GitHub בדפדפן", pt: "Abre o GitHub no navegador", tr: "Tarayıcıda GitHub açar").dict,
    "feedback.email": Tr(zh: "改用邮件", en: "Email instead", hant: "改用郵件", ja: "メールにする", ko: "이메일로 보내기", es: "Mejor por correo", ar: "البريد بدلًا من ذلك", de: "Lieber per E-Mail", fr: "Plutôt par e-mail", he: "במקום זאת במייל", pt: "Melhor por e-mail", tr: "E-posta ile gönder").dict,
    "feedback.email.sub": Tr(zh: "sirouni@msn.com", en: "sirouni@msn.com", hant: "sirouni@msn.com", ja: "sirouni@msn.com", ko: "sirouni@msn.com", es: "sirouni@msn.com", ar: "sirouni@msn.com", de: "sirouni@msn.com", fr: "sirouni@msn.com", he: "sirouni@msn.com", pt: "sirouni@msn.com", tr: "sirouni@msn.com").dict,
    "color.red": Tr(zh: "红", en: "Red", hant: "紅", ja: "赤", ko: "빨강", es: "Rojo", ar: "أحمر", de: "Rot", fr: "Rouge", he: "אדום", pt: "Vermelho", tr: "Kırmızı").dict,
    "color.green": Tr(zh: "绿", en: "Green", hant: "綠", ja: "緑", ko: "초록", es: "Verde", ar: "أخضر", de: "Grün", fr: "Vert", he: "ירוק", pt: "Verde", tr: "Yeşil").dict,
    "color.blue": Tr(zh: "蓝", en: "Blue", hant: "藍", ja: "青", ko: "파랑", es: "Azul", ar: "أزرق", de: "Blau", fr: "Bleu", he: "כחול", pt: "Azul", tr: "Mavi").dict,
    "color.yellow": Tr(zh: "黄", en: "Yellow", hant: "黃", ja: "黄", ko: "노랑", es: "Amarillo", ar: "أصفر", de: "Gelb", fr: "Jaune", he: "צהוב", pt: "Amarelo", tr: "Sarı").dict,
    "color.purple": Tr(zh: "紫", en: "Purple", hant: "紫", ja: "紫", ko: "보라", es: "Morado", ar: "بنفسجي", de: "Lila", fr: "Violet", he: "סגול", pt: "Roxo", tr: "Mor").dict,
    "color.orange": Tr(zh: "橙", en: "Orange", hant: "橙", ja: "オレンジ", ko: "주황", es: "Naranja", ar: "برتقالي", de: "Orange", fr: "Orange", he: "כתום", pt: "Laranja", tr: "Turuncu").dict,
    "color.cyan": Tr(zh: "青", en: "Cyan", hant: "青", ja: "シアン", ko: "청록", es: "Cian", ar: "سماوي", de: "Cyan", fr: "Cyan", he: "ציאן", pt: "Ciano", tr: "Camgöbeği").dict,
    "color.pink": Tr(zh: "粉", en: "Pink", hant: "粉", ja: "ピンク", ko: "분홍", es: "Rosa", ar: "وردي", de: "Pink", fr: "Rose", he: "ורוד", pt: "Rosa", tr: "Pembe").dict,
    "daily.title": Tr(zh: "每日挑战", en: "Daily Challenge", hant: "每日挑戰", ja: "デイリーチャレンジ", ko: "일일 도전", es: "Desafío diario", ar: "التحدي اليومي", de: "Tägliche Herausforderung", fr: "Défi du jour", he: "אתגר יומי", pt: "Desafio diário", tr: "Günlük görev").dict,
    "daily.completed": Tr(zh: "今日挑战已完成", en: "Today's challenge complete", hant: "今日挑戰已完成", ja: "今日の挑戦は完了", ko: "오늘의 도전 완료", es: "Reto de hoy completado", ar: "تحدي اليوم اكتمل", de: "Heutige Challenge fertig", fr: "Défi du jour terminé", he: "האתגר היומי הושלם", pt: "Desafio de hoje concluído", tr: "Bugünün görevi bitti").dict,
    "daily.tomorrow": Tr(zh: "明天再来挑战新密码！", en: "Come back tomorrow!", hant: "明天再來挑戰新密碼！", ja: "また明日、新しいコードを", ko: "내일 새 암호로 다시 도전하세요!", es: "¡Vuelve mañana!", ar: "عد غدًا!", de: "Komm morgen wieder!", fr: "Reviens demain !", he: "תחזור מחר!", pt: "Volte amanhã!", tr: "Yarın yine gel!").dict,
    "daily.start": Tr(zh: "开始挑战", en: "Start", hant: "開始挑戰", ja: "始める", ko: "시작", es: "Empezar", ar: "ابدأ", de: "Start", fr: "Commencer", he: "התחל", pt: "Começar", tr: "Başla").dict,
    "daily.back": Tr(zh: "返回首页", en: "Back to Home", hant: "返回首頁", ja: "ホームへ", ko: "홈으로", es: "Volver al inicio", ar: "العودة للرئيسية", de: "Zur Startseite", fr: "Retour à l’accueil", he: "חזרה לבית", pt: "Voltar ao início", tr: "Ana sayfaya").dict,
    "editor.title": Tr(zh: "自定义关卡", en: "Custom Level", hant: "自訂關卡", ja: "カスタムレベル", ko: "커스텀 레벨", es: "Nivel personalizado", ar: "مستوى مخصص", de: "Eigenes Level", fr: "Niveau perso", he: "שלב מותאם", pt: "Nível personalizado", tr: "Özel seviye").dict,
    "editor.start": Tr(zh: "开始自定义挑战", en: "Start Custom Challenge", hant: "開始自訂挑戰", ja: "カスタム挑戦を始める", ko: "커스텀 도전 시작", es: "Empezar reto propio", ar: "ابدأ التحدي المخصص", de: "Eigenes Level starten", fr: "Lancer le défi perso", he: "התחל שלב מותאם", pt: "Começar desafio próprio", tr: "Özel göreve başla").dict,
    "menu.online": Tr(zh: "在线对战", en: "Online Match", hant: "線上對戰", ja: "オンライン対戦", ko: "온라인 대전", es: "Partida online", ar: "مباراة عبر الإنترنت", de: "Online-Match", fr: "Match en ligne", he: "משחק מקוון", pt: "Partida online", tr: "Çevrimiçi maç").dict,
    "menu.online.sub": Tr(zh: "Game Center 实时竞速", en: "Game Center speed duel", hant: "Game Center 即時競速", ja: "Game Centerでスピード対決", ko: "Game Center 실시간 대결", es: "Duelo rápido en Game Center", ar: "سباق Game Center مباشر", de: "Game-Center-Tempo-Duell", fr: "Duel rapide Game Center", he: "דו-קרב מהיר ב‑Game Center", pt: "Duelo rápido no Game Center", tr: "Game Center hız düellosu").dict,
    "online.title": Tr(zh: "在线对战", en: "Online Match", hant: "線上對戰", ja: "オンライン対戦", ko: "온라인 대전", es: "Partida online", ar: "مباراة عبر الإنترنت", de: "Online-Match", fr: "Match en ligne", he: "משחק מקוון", pt: "Partida online", tr: "Çevrimiçi maç").dict,
    "online.desc": Tr(zh: "与全球玩家实时竞速破译", en: "Race against players worldwide", hant: "與全球玩家即時競速破譯", ja: "世界中のプレイヤーと解読レース", ko: "전 세계 플레이어와 해독 경쟁", es: "Compite contra jugadores de todo el mundo", ar: "تسابق لاعبين حول العالم", de: "Renne gegen Spieler weltweit", fr: "Course contre des joueurs du monde", he: "התחרה בשחקנים ברחבי העולם", pt: "Dispute com jogadores do mundo", tr: "Dünyadaki oyuncularla yarış").dict,
    "online.find": Tr(zh: "寻找对手", en: "Find Match", hant: "尋找對手", ja: "対戦相手を探す", ko: "상대 찾기", es: "Buscar partida", ar: "البحث عن مباراة", de: "Match suchen", fr: "Trouver un match", he: "חפש משחק", pt: "Buscar partida", tr: "Maç ara").dict,
    "online.searching": Tr(zh: "正在匹配对手…", en: "Searching for opponent…", hant: "正在配對對手…", ja: "対戦相手を探しています…", ko: "상대를 찾는 중…", es: "Buscando rival…", ar: "جاري البحث عن خصم…", de: "Suche Gegner…", fr: "Recherche d’adversaire…", he: "מחפש יריב…", pt: "Procurando rival…", tr: "Rakip aranıyor…").dict,
    "online.waiting": Tr(zh: "等待对手就绪…", en: "Waiting for opponent…", hant: "等待對手就緒…", ja: "相手の準備待ち…", ko: "상대 준비 대기 중…", es: "Esperando al rival…", ar: "بانتظار جاهزية الخصم…", de: "Warte auf Gegner…", fr: "En attente du rival…", he: "ממתין ליריב…", pt: "Aguardando o rival…", tr: "Rakip bekleniyor…").dict,
    "online.gc.required": Tr(zh: "请先登录 Game Center", en: "Sign in to Game Center first", hant: "請先登入 Game Center", ja: "先にGame Centerへサインイン", ko: "먼저 Game Center에 로그인하세요", es: "Entra primero en Game Center", ar: "سجّل الدخول إلى Game Center أولًا", de: "Zuerst bei Game Center anmelden", fr: "Connecte-toi d’abord à Game Center", he: "היכנס קודם ל‑Game Center", pt: "Entre no Game Center primeiro", tr: "Önce Game Center’a giriş yap").dict,
    "online.disconnected": Tr(zh: "%@ 已断开连接", en: "%@ disconnected", hant: "%@ 已中斷連線", ja: "%@が切断されました", ko: "%@의 연결이 끊겼습니다", es: "%@ se desconectó", ar: "انقطع %@", de: "%@ getrennt", fr: "%@ déconnecté", he: "%@ התנתק", pt: "%@ desconectou", tr: "%@ bağlantısı koptu").dict,
    "online.rules.title": Tr(zh: "对战规则", en: "Rules", hant: "對戰規則", ja: "ルール", ko: "규칙", es: "Reglas", ar: "القواعد", de: "Regeln", fr: "Règles", he: "כללים", pt: "Regras", tr: "Kurallar").dict,
    "online.rule1": Tr(zh: "1. 匹配成功后双方破解同一密码", en: "1. Both players crack the same code", hant: "1. 配對成功後雙方破解同一密碼", ja: "1. 同じコードを双方が解読", ko: "1. 매칭되면 같은 암호를 풉니다", es: "1. Ambos descifran el mismo código", ar: "1. يفك الطرفان الرمز نفسه", de: "1. Beide knacken denselben Code", fr: "1. Les deux cassent le même code", he: "1. שני השחקנים מפצחים את אותו קוד", pt: "1. Ambos decifram o mesmo código", tr: "1. İkiniz de aynı kodu çözersiniz").dict,
    "online.rule2": Tr(zh: "2. 先破解者获胜", en: "2. First to solve wins", hant: "2. 先破解者獲勝", ja: "2. 先に解読した方が勝ち", ko: "2. 먼저 푸는 사람이 승리", es: "2. Gana quien lo resuelva primero", ar: "2. من يفك أولًا يفوز", de: "2. Wer zuerst löst, gewinnt", fr: "2. Le premier à résoudre gagne", he: "2. הראשון שפותר מנצח", pt: "2. Quem resolver primeiro vence", tr: "2. İlk çözen kazanır").dict,
    "online.rule3": Tr(zh: "3. 步数相同则用时短者胜", en: "3. Fewer steps wins; ties broken by time", hant: "3. 步數相同則用時短者勝", ja: "3. 同手数なら早い方が勝ち", ko: "3. 수가 같으면 더 빠른 쪽이 이깁니다", es: "3. Menos pasos gana; empate por tiempo", ar: "3. عند تساوي الخطوات يفوز الأسرع", de: "3. Weniger Züge siegen; Gleichstand nach Zeit", fr: "3. Moins de coups gagne ; égalité au temps", he: "3. פחות מהלכים מנצחים; תיקו לפי זמן", pt: "3. Menos passos vence; empate por tempo", tr: "3. Daha az hamle kazanır; beraberlikte süre").dict,
    "online.steps": Tr(zh: "步", en: "steps", hant: "步", ja: "手", ko: "수", es: "pasos", ar: "خطوات", de: "Züge", fr: "coups", he: "מהלכים", pt: "passos", tr: "hamle").dict,
    "online.rematch": Tr(zh: "再来一局", en: "Rematch", hant: "再來一局", ja: "再戦", ko: "재대결", es: "Revancha", ar: "إعادة المباراة", de: "Revanche", fr: "Revanche", he: "משחק חוזר", pt: "Revanche", tr: "Rövanş").dict,
    "online.exit": Tr(zh: "退出对战", en: "Exit Match", hant: "退出對戰", ja: "対戦をやめる", ko: "대전 나가기", es: "Salir", ar: "مغادرة المباراة", de: "Match verlassen", fr: "Quitter le match", he: "יציאה מהמשחק", pt: "Sair da partida", tr: "Maçtan çık").dict,
    "online.timeout": Tr(zh: "连接超时，请重新匹配", en: "Connection timed out. Please try again", hant: "連線逾時，請重新配對", ja: "接続が切れました。もう一度探して", ko: "연결 시간이 초과되었습니다. 다시 시도하세요", es: "Tiempo agotado. Inténtalo de nuevo", ar: "انتهت مهلة الاتصال. حاول مجددًا", de: "Zeitüberschreitung. Bitte erneut versuchen", fr: "Délai dépassé. Réessaie", he: "החיבור פג. נסה שוב", pt: "Tempo esgotado. Tente de novo", tr: "Bağlantı zaman aşımı. Tekrar dene").dict,
    "online.opponent.left": Tr(zh: "对手已离开", en: "Opponent left", hant: "對手已離開", ja: "相手が離脱しました", ko: "상대가 나갔습니다", es: "El rival se fue", ar: "غادر الخصم", de: "Gegner hat verlassen", fr: "Le rival est parti", he: "היריב עזב", pt: "O rival saiu", tr: "Rakip ayrıldı").dict,
    "online.you.win": Tr(zh: "你赢了！", en: "You Win!", hant: "你贏了！", ja: "あなたの勝ち！", ko: "승리!", es: "¡Ganaste!", ar: "لقد فزت!", de: "Du gewinnst!", fr: "Tu gagnes !", he: "ניצחת!", pt: "Você venceu!", tr: "Kazandın!").dict,
    "online.you.lose": Tr(zh: "你输了", en: "You Lose", hant: "你輸了", ja: "あなたの負け", ko: "패배", es: "Perdiste", ar: "خسرت", de: "Du verlierst", fr: "Tu perds", he: "הפסדת", pt: "Você perdeu", tr: "Kaybettin").dict,
    "online.draw": Tr(zh: "平局", en: "Draw", hant: "平局", ja: "引き分け", ko: "무승부", es: "Empate", ar: "تعادل", de: "Unentschieden", fr: "Match nul", he: "תיקו", pt: "Empate", tr: "Berabere").dict,
    "paywall.unlock": Tr(zh: "解锁 Pro", en: "Unlock Pro", hant: "解鎖 Pro", ja: "Proを解除", ko: "Pro 잠금 해제", es: "Desbloquear Pro", ar: "فتح Pro", de: "Pro freischalten", fr: "Débloquer Pro", he: "פתח Pro", pt: "Desbloquear Pro", tr: "Pro’yu aç").dict,
    "paywall.restore": Tr(zh: "恢复购买", en: "Restore Purchases", hant: "恢復購買", ja: "購入を復元", ko: "구매 복원", es: "Restaurar compras", ar: "استعادة المشتريات", de: "Käufe wiederherstellen", fr: "Restaurer les achats", he: "שחזר רכישות", pt: "Restaurar compras", tr: "Satın alımları geri yükle").dict,
    "paywall.price": Tr(zh: "一次买断", en: "One-time unlock", hant: "一次買斷", ja: "買い切り", ko: "한 번만 결제", es: "Pago único", ar: "شراء لمرة واحدة", de: "Einmaliger Kauf", fr: "Achat unique", he: "רכישה חד־פעמית", pt: "Pagamento único", tr: "Tek seferlik").dict,
    "paywall.benefit.lie": Tr(zh: "谎言任务后半段：交叉验证假线索", en: "The rest of Lie Missions — cross-check the fake clue", hant: "謊言任務後半段：交叉驗證假線索", ja: "嘘の任務の後半 — 嘘を突き合わせる", ko: "거짓말 임무 후반 — 가짜 단서를 교차 검증", es: "El resto de Mentira — cruza la pista falsa", ar: "بقية مهام الكذب — تحقق من الدليل المزيف", de: "Rest der Lügen-Missionen — den falschen Hinweis abgleichen", fr: "Le reste des Missions Mensonge — recoupe l’indice faux", he: "שאר משימות השקר — להצליב את הרמז המזויף", pt: "O resto de Mentira — cruze a pista falsa", tr: "Yalan görevlerinin gerisi — sahte ipucunu çaprazla").dict,
    "paywall.benefit.classic": Tr(zh: "经典任务剩余关卡", en: "Remaining Classic Missions", hant: "經典任務剩餘關卡", ja: "残りのクラシック任務", ko: "남은 클래식 임무", es: "Resto de misiones clásicas", ar: "بقية المهام الكلاسيكية", de: "Restliche Klassik-Missionen", fr: "Missions classiques restantes", he: "שאר המשימות הקלאסיות", pt: "Restante das missões clássicas", tr: "Kalan klasik görevler").dict,
    "paywall.benefit.free": Tr(zh: "自由模式（可开谎言）", en: "Free Play, including Lie Mode", hant: "自由模式（可開謊言）", ja: "フリープレイ（嘘モード可）", ko: "자유 플레이 (거짓말 모드 포함)", es: "Juego libre, con Modo Mentira", ar: "لعب حر، يشمل وضع الكذب", de: "Freies Spiel inkl. Lügenmodus", fr: "Partie libre, Mode Mensonge inclus", he: "משחק חופשי, כולל מצב שקר", pt: "Jogo livre, com Modo Mentira", tr: "Serbest oyun, Yalan modu dahil").dict,
    "paywall.benefit.editor": Tr(zh: "自定义关卡编辑器", en: "Custom Level Editor", hant: "自訂關卡編輯器", ja: "カスタムレベル編集", ko: "커스텀 레벨 편집기", es: "Editor de niveles", ar: "محرر المستويات", de: "Level-Editor", fr: "Éditeur de niveaux", he: "עורך שלבים", pt: "Editor de níveis", tr: "Seviye editörü").dict,
    "paywall.classic.title": Tr(zh: "继续深入", en: "Go deeper", hant: "繼續深入", ja: "もっと先へ", ko: "더 깊이", es: "Sigue adelante", ar: "تعمّق أكثر", de: "Tiefer gehen", fr: "Va plus loin", he: "להעמיק", pt: "Vá mais fundo", tr: "Daha derine").dict,
    "paywall.classic.sub": Tr(zh: "解锁经典 41–240 关、完整谎言战役、自由模式和编辑器。", en: "Unlock Classic 41–240, the full Lie campaign, Free Play, and the editor.", hant: "解鎖經典 41–240 關、完整謊言戰役、自由模式和編輯器。", ja: "クラシック41–240、嘘キャンペーン全部、フリープレイと編集を解除。", ko: "클래식 41–240, 거짓말 캠페인 전체, 자유 플레이와 편집기를 해제하세요.", es: "Desbloquea Clásico 41–240, toda la campaña Mentira, juego libre y el editor.", ar: "افتح الكلاسيكي 41–240، حملة الكذب كاملة، اللعب الحر والمحرر.", de: "Schalte Klassik 41–240, die volle Lügen-Kampagne, Freies Spiel und den Editor frei.", fr: "Débloque Classique 41–240, toute la campagne Mensonge, la partie libre et l’éditeur.", he: "פתח קלאסי 41–240, את כל מסע השקר, משחק חופשי ואת העורך.", pt: "Desbloqueie Clássico 41–240, a campanha Mentira inteira, jogo livre e o editor.", tr: "Klasik 41–240, tüm Yalan kampanyası, serbest oyun ve editörü aç.").dict,
    "paywall.lie.title": Tr(zh: "继续识破谎言", en: "Keep hunting lies", hant: "繼續識破謊言", ja: "嘘を追い続ける", ko: "거짓을 계속 찾아내세요", es: "Sigue cazando mentiras", ar: "واصل اصطياد الكذب", de: "Weiter Lügen jagen", fr: "Continue à chasser les mensonges", he: "המשך לצוד שקרים", pt: "Continue caçando mentiras", tr: "Yalan avına devam").dict,
    "paywall.lie.sub": Tr(zh: "后面的关需要真正交叉验证。解锁谎言 81–240 关和全部内容。", en: "The next missions need real cross-checks. Unlock Lie 81–240 and the rest of the game.", hant: "後面的關需要真正交叉驗證。解鎖謊言 81–240 關和全部內容。", ja: "この先は突き合わせが必要。嘘81–240と残り全部を解除。", ko: "앞으로는 진짜 교차 검증이 필요합니다. 거짓말 81–240과 나머지를 해제하세요.", es: "Lo que sigue exige cruzar pistas. Desbloquea Mentira 81–240 y el resto.", ar: "المهام التالية تحتاج تحققًا متقاطعًا. افتح الكذب 81–240 وبقية اللعبة.", de: "Die nächsten Missionen brauchen echtes Abgleichen. Schalte Lüge 81–240 und den Rest frei.", fr: "La suite exige de vraies recoupes. Débloque Mensonge 81–240 et le reste.", he: "המשימות הבאות דורשות הצלבות אמיתיות. פתח שקר 81–240 ואת שאר המשחק.", pt: "O que vem exige cruzar pistas de verdade. Desbloqueie Mentira 81–240 e o resto.", tr: "Sıradaki görevler gerçek çapraz kontrol ister. Yalan 81–240 ve oyunun gerisini aç.").dict,
    "paywall.free.title": Tr(zh: "自由模式需要 Pro", en: "Free Play is Pro", hant: "自由模式需要 Pro", ja: "フリープレイはPro", ko: "자유 플레이는 Pro", es: "El juego libre es Pro", ar: "اللعب الحر يتطلب Pro", de: "Freies Spiel ist Pro", fr: "La partie libre est Pro", he: "משחק חופשי הוא Pro", pt: "O jogo livre é Pro", tr: "Serbest oyun Pro").dict,
    "paywall.free.sub": Tr(zh: "自选难度，也可打开谎言，不走战役格子。", en: "Pick any difficulty — including Lie — and play without the campaign grid.", hant: "自選難度，也可打開謊言，不走戰役格子。", ja: "難易度も嘘モードも自由。キャンペーン盤は使わない。", ko: "난이도와 거짓말 모드를 고르고, 캠페인 칸 없이 플레이하세요.", es: "Elige dificultad — también Mentira — sin la cuadrícula de campaña.", ar: "اختر أي صعوبة — بما فيها الكذب — دون شبكة الحملة.", de: "Beliebige Schwierigkeit — inkl. Lüge — ohne Kampagnenraster.", fr: "Choisis n’importe quelle difficulté — Mensonge compris — sans la grille de campagne.", he: "בחר כל קושי — כולל שקר — בלי לוח המסע.", pt: "Escolha qualquer dificuldade — inclusive Mentira — sem a grade da campanha.", tr: "İstediğin zorluğu seç — Yalan dahil — kampanya ızgarası olmadan.").dict,
    "paywall.editor.title": Tr(zh: "关卡编辑器需要 Pro", en: "Editor is Pro", hant: "關卡編輯器需要 Pro", ja: "編集はPro", ko: "편집기는 Pro", es: "El editor es Pro", ar: "المحرر يتطلب Pro", de: "Editor ist Pro", fr: "L’éditeur est Pro", he: "העורך הוא Pro", pt: "O editor é Pro", tr: "Editör Pro").dict,
    "paywall.editor.sub": Tr(zh: "自己做题、分享给朋友。", en: "Build puzzles and share them with a friend.", hant: "自己做題、分享給朋友。", ja: "自分で問題を作り、友だちに送る。", ko: "퍼즐을 만들어 친구에게 공유하세요.", es: "Crea puzzles y compártelos con un amigo.", ar: "اصنع ألغازًا وشاركها مع صديق.", de: "Baue Rätsel und teile sie mit Freunden.", fr: "Crée des puzzles et envoie-les à un ami.", he: "בנה חידות ושתף עם חבר.", pt: "Crie puzzles e compartilhe com um amigo.", tr: "Bulmaca yap, arkadaşınla paylaş.").dict,
    "paywall.done.classic.title": Tr(zh: "初级特工毕业", en: "Junior Agent complete", hant: "初級特工畢業", ja: "見習い卒業", ko: "초급 요원 수료", es: "Agente junior completado", ar: "تخرّج العميل المبتدئ", de: "Junior-Agent abgeschlossen", fr: "Agent junior terminé", he: "הסוכן הזוטר סיים", pt: "Agente júnior concluído", tr: "Çaylak ajan tamam").dict,
    "paywall.done.classic.sub": Tr(zh: "规则你已经会了。解锁后面的经典关，以及更深的谎言任务。", en: "You've got the rules. Unlock the rest of Classic and the deeper Lie campaign.", hant: "規則你已經會了。解鎖後面的經典關，以及更深的謊言任務。", ja: "ルールはもうわかった。残りのクラシックと、より深い嘘の任務を解除。", ko: "규칙은 이미 익혔습니다. 나머지 클래식과 더 깊은 거짓말 임무를 해제하세요.", es: "Ya sabes las reglas. Desbloquea el resto de Clásico y la campaña Mentira más profunda.", ar: "القواعد صارت واضحة. افتح بقية الكلاسيكي وحملة الكذب الأعمق.", de: "Die Regeln sitzen. Schalte den Rest von Klassik und die tiefere Lügen-Kampagne frei.", fr: "Tu as les règles. Débloque le reste de Classique et la campagne Mensonge plus profonde.", he: "הכללים כבר ברורים. פתח את שאר הקלאסי ואת מסע השקר העמוק יותר.", pt: "Você já sabe as regras. Desbloqueie o resto do Clássico e a campanha Mentira mais profunda.", tr: "Kuralları öğrendin. Klasik’in gerisini ve daha derin Yalan kampanyasını aç.").dict,
    "paywall.done.lie.title": Tr(zh: "你已经能识破谎言", en: "You can spot a lie", hant: "你已經能識破謊言", ja: "嘘は見抜ける", ko: "거짓을 알아볼 수 있습니다", es: "Ya detectas una mentira", ar: "تستطيع رصد الكذبة", de: "Du erkennst eine Lüge", fr: "Tu repères un mensonge", he: "אתה מזהה שקר", pt: "Você já percebe uma mentira", tr: "Yalanı görebiliyorsun").dict,
    "paywall.done.lie.sub": Tr(zh: "后面要交叉验证线索。$2.99 解锁剩余谎言关和全部内容。", en: "Now the clues need cross-checking. Unlock the rest of Lie Mode and the full game.", hant: "後面要交叉驗證線索。$2.99 解鎖剩餘謊言關和全部內容。", ja: "この先は手がかりの突き合わせ。残りの嘘モードと全部を解除。", ko: "이제는 단서를 교차 검증해야 합니다. 나머지 거짓말 모드와 전체 게임을 해제하세요.", es: "Ahora hay que cruzar pistas. Desbloquea el resto de Mentira y el juego completo.", ar: "الآن تحتاج الأدلة تحققًا متقاطعًا. افتح بقية وضع الكذب واللعبة كاملة.", de: "Jetzt müssen Hinweise abgeglichen werden. Schalte den Rest des Lügenmodus und das volle Spiel frei.", fr: "Désormais il faut recouper. Débloque le reste du Mode Mensonge et tout le jeu.", he: "עכשיו צריך להצליב רמזים. פתח את שאר מצב השקר ואת כל המשחק.", pt: "Agora as pistas pedem cruzamento. Desbloqueie o resto do Modo Mentira e o jogo todo.", tr: "Artık ipuçlarını çaprazlaman gerek. Yalan modunun gerisini ve tüm oyunu aç.").dict,
    "store.pro.blurb": Tr(zh: "更深的谎言任务、剩余战役、自由模式和编辑器", en: "Deeper Lie missions, remaining campaign, Free Play & editor", hant: "更深的謊言任務、剩餘戰役、自由模式和編輯器", ja: "より深い嘘の任務、残りのキャンペーン、フリープレイと編集", ko: "더 깊은 거짓말 임무, 남은 캠페인, 자유 플레이와 편집기", es: "Misiones Mentira más profundas, campaña restante, juego libre y editor", ar: "مهام كذب أعمق، بقية الحملة، لعب حر ومحرر", de: "Tiefere Lügen-Missionen, restliche Kampagne, Freies Spiel & Editor", fr: "Missions Mensonge plus profondes, campagne restante, partie libre et éditeur", he: "משימות שקר עמוקות יותר, שאר המסע, משחק חופשי ועורך", pt: "Missões Mentira mais profundas, campanha restante, jogo livre e editor", tr: "Daha derin Yalan görevleri, kalan kampanya, serbest oyun ve editör").dict,
    "store.pro.done": Tr(zh: "Pro 已解锁", en: "Pro unlocked", hant: "Pro 已解鎖", ja: "Pro解除済み", ko: "Pro 해제됨", es: "Pro desbloqueado", ar: "Pro مفتوح", de: "Pro freigeschaltet", fr: "Pro débloqué", he: "Pro נפתח", pt: "Pro desbloqueado", tr: "Pro açık").dict,
    "store.title": Tr(zh: "商店", en: "Store", hant: "商店", ja: "ストア", ko: "스토어", es: "Tienda", ar: "المتجر", de: "Store", fr: "Boutique", he: "חנות", pt: "Loja", tr: "Mağaza").dict,
    "store.unlock": Tr(zh: "解锁完整游戏", en: "Unlock Full Game", hant: "解鎖完整遊戲", ja: "ゲーム全体を解除", ko: "전체 게임 잠금 해제", es: "Desbloquear el juego", ar: "فتح اللعبة كاملة", de: "Ganzes Spiel freischalten", fr: "Débloquer tout le jeu", he: "פתח את כל המשחק", pt: "Desbloquear o jogo", tr: "Tüm oyunu aç").dict,
    "store.hints": Tr(zh: "提示币", en: "Hint Coins", hant: "提示幣", ja: "ヒントコイン", ko: "힌트 코인", es: "Monedas de pista", ar: "عملات التلميح", de: "Tipp-Münzen", fr: "Pièces d’indice", he: "מטבעות רמז", pt: "Moedas de dica", tr: "İpucu jetonu").dict,
    "legend.exact": Tr(zh: "= 颜色对，位置也对", en: "= One right color in the right position", hant: "= 顏色對，位置也對", ja: "＝ 色も位置も正しい", ko: "= 색과 위치가 모두 맞음", es: "= Un color bien, en el sitio correcto", ar: "= لون صحيح في المكان الصحيح", de: "= Richtige Farbe am richtigen Platz", fr: "= Bonne couleur au bon endroit", he: "= צבע נכון במקום הנכון", pt: "= Cor certa no lugar certo", tr: "= Doğru renk, doğru yer").dict,
    "legend.partial": Tr(zh: "= 颜色对，位置不对", en: "= One right color but in the wrong position", hant: "= 顏色對，位置不對", ja: "＝ 色は正しいが位置が違う", ko: "= 색은 맞지만 위치가 다름", es: "= Color bien, sitio mal", ar: "= لون صحيح في مكان خطأ", de: "= Richtige Farbe, falscher Platz", fr: "= Bonne couleur, mauvais endroit", he: "= צבע נכון, מקום שגוי", pt: "= Cor certa, lugar errado", tr: "= Doğru renk, yanlış yer").dict,
    "legend.miss": Tr(zh: "= 这个颜色不在密码里", en: "= One color is not in the secret code", hant: "= 這個顏色不在密碼裡", ja: "＝ その色はコードにない", ko: "= 이 색은 암호에 없음", es: "= Ese color no está en el código", ar: "= هذا اللون ليس في الرمز السري", de: "= Diese Farbe ist nicht im Geheimcode", fr: "= Cette couleur n’est pas dans le code", he: "= הצבע הזה לא בקוד הסודי", pt: "= Essa cor não está no código", tr: "= Bu renk gizli kodda yok").dict,
    "game.notes": Tr(zh: "笔记", en: "Notes", hant: "筆記", ja: "メモ", ko: "노트", es: "Notas", ar: "ملاحظات", de: "Notizen", fr: "Notes", he: "פתקים", pt: "Notas", tr: "Notlar").dict,
    "game.notes.clear": Tr(zh: "清除", en: "Clear", hant: "清除", ja: "消去", ko: "지우기", es: "Borrar", ar: "مسح", de: "Löschen", fr: "Effacer", he: "נקה", pt: "Limpar", tr: "Temizle").dict,
    "game.score": Tr(zh: "得分：%d", en: "Score: %d", hant: "得分：%d", ja: "スコア：%d", ko: "점수: %d", es: "Puntos: %d", ar: "النقاط: %d", de: "Punkte: %d", fr: "Score : %d", he: "ניקוד: %d", pt: "Pontos: %d", tr: "Skor: %d").dict,
    "game.submitted": Tr(zh: "已提交", en: "Submitted!", hant: "已提交", ja: "送信済み", ko: "제출됨", es: "¡Enviado!", ar: "أُرسل!", de: "Gesendet!", fr: "Envoyé !", he: "נשלח!", pt: "Enviado!", tr: "Gönderildi!").dict,
    "game.hint.earned": Tr(zh: "+1 提示币！（现有 %d）", en: "+1 Hint Coin! (%d total)", hant: "+1 提示幣！（現有 %d）", ja: "ヒントコイン+1！（合計%d）", ko: "힌트 코인 +1! (총 %d)", es: "¡+1 moneda de pista! (%d en total)", ar: "+1 عملة تلميح! (المجموع %d)", de: "+1 Tipp-Münze! (%d gesamt)", fr: "+1 pièce d’indice ! (%d au total)", he: "+1 מטבע רמז! (סה״כ %d)", pt: "+1 moeda de dica! (%d no total)", tr: "+1 ipucu jetonu! (toplam %d)").dict,
    "game.hint.progress": Tr(zh: "%d/%d 局后得下一枚", en: "%d/%d wins to next coin", hant: "%d/%d 局後得下一枚", ja: "次のコインまで %d/%d勝", ko: "다음 코인까지 %d/%d승", es: "%d/%d victorias para la siguiente", ar: "%d/%d فوز للعملة التالية", de: "%d/%d Siege zur nächsten Münze", fr: "%d/%d victoires pour la suivante", he: "%d/%d ניצחונות למטבע הבא", pt: "%d/%d vitórias para a próxima", tr: "Sonraki jeton için %d/%d galibiyet").dict,
    "result.challenge": Tr(zh: "向朋友发起挑战", en: "Challenge a Friend", hant: "向朋友發起挑戰", ja: "友だちに挑戦状", ko: "친구에게 도전장", es: "Reta a un amigo", ar: "تحدَّ صديقًا", de: "Freund herausfordern", fr: "Défie un ami", he: "אתגר חבר", pt: "Desafie um amigo", tr: "Arkadaşına meydan oku").dict,
    "achieve.toast": Tr(zh: "解锁成就！", en: "Achievement Unlocked!", hant: "解鎖成就！", ja: "実績解除！", ko: "업적 해제!", es: "¡Logro desbloqueado!", ar: "إنجاز مفتوح!", de: "Erfolg freigeschaltet!", fr: "Succès débloqué !", he: "הישג נפתח!", pt: "Conquista desbloqueada!", tr: "Başarım açıldı!").dict,
    "home.streak.fire": Tr(zh: "连胜 %d！", en: "Streak %d!", hant: "連勝 %d！", ja: "%d連勝！", ko: "%d연승!", es: "¡Racha de %d!", ar: "سلسلة %d!", de: "Serie %d!", fr: "Série de %d !", he: "רצף %d!", pt: "Sequência de %d!", tr: "%d seri!").dict,
    "home.streak.best": Tr(zh: "最佳 %d", en: "Best %d", hant: "最佳 %d", ja: "最高 %d", ko: "최고 %d", es: "Mejor %d", ar: "أفضل %d", de: "Beste %d", fr: "Meilleur %d", he: "שיא %d", pt: "Melhor %d", tr: "En iyi %d").dict,
    "home.unlocked": Tr(zh: "%d/%d 已解锁", en: "%d/%d unlocked", hant: "%d/%d 已解鎖", ja: "%d/%d 解除", ko: "%d/%d 해제", es: "%d/%d desbloqueados", ar: "%d/%d مفتوح", de: "%d/%d frei", fr: "%d/%d débloqués", he: "%d/%d נפתחו", pt: "%d/%d desbloqueados", tr: "%d/%d açık").dict,
    "settings.game": Tr(zh: "游戏", en: "Game", hant: "遊戲", ja: "ゲーム", ko: "게임", es: "Juego", ar: "اللعبة", de: "Spiel", fr: "Jeu", he: "משחק", pt: "Jogo", tr: "Oyun").dict,
    "settings.theme": Tr(zh: "主题", en: "Theme", hant: "主題", ja: "テーマ", ko: "테마", es: "Tema", ar: "المظهر", de: "Design", fr: "Thème", he: "ערכת נושא", pt: "Tema", tr: "Tema").dict,
    "settings.stats": Tr(zh: "统计", en: "Stats", hant: "統計", ja: "記録", ko: "통계", es: "Estadísticas", ar: "الإحصاءات", de: "Statistik", fr: "Stats", he: "סטטיסטיקה", pt: "Estatísticas", tr: "İstatistik").dict,
    "settings.manage": Tr(zh: "管理", en: "Manage", hant: "管理", ja: "管理", ko: "관리", es: "Gestionar", ar: "إدارة", de: "Verwalten", fr: "Gérer", he: "ניהול", pt: "Gerenciar", tr: "Yönet").dict,
    "settings.about": Tr(zh: "关于", en: "About", hant: "關於", ja: "このアプリ", ko: "정보", es: "Acerca de", ar: "حول", de: "Info", fr: "À propos", he: "אודות", pt: "Sobre", tr: "Hakkında").dict,
    "settings.wins": Tr(zh: "胜场", en: "Wins", hant: "勝場", ja: "勝利", ko: "승리", es: "Victorias", ar: "انتصارات", de: "Siege", fr: "Victoires", he: "ניצחונות", pt: "Vitórias", tr: "Galibiyet").dict,
    "settings.beststreak": Tr(zh: "最长连胜", en: "Best streak", hant: "最長連勝", ja: "最多連勝", ko: "최장 연승", es: "Mejor racha", ar: "أفضل سلسلة", de: "Beste Serie", fr: "Meilleure série", he: "רצף שיא", pt: "Melhor sequência", tr: "En uzun seri").dict,
    "settings.avg": Tr(zh: "平均步数", en: "Avg steps", hant: "平均步數", ja: "平均手数", ko: "평균 수", es: "Pasos medios", ar: "متوسط الخطوات", de: "Ø Züge", fr: "Coups moy.", he: "מהלכים ממוצע", pt: "Passos médios", tr: "Ort. hamle").dict,
    "settings.levels": Tr(zh: "已完成关卡", en: "Levels done", hant: "已完成關卡", ja: "クリアしたレベル", ko: "완료한 레벨", es: "Niveles hechos", ar: "مستويات مكتملة", de: "Level geschafft", fr: "Niveaux finis", he: "שלבים שהושלמו", pt: "Níveis feitos", tr: "Bitirilen seviye").dict,
    "settings.version": Tr(zh: "版本", en: "Version", hant: "版本", ja: "バージョン", ko: "버전", es: "Versión", ar: "الإصدار", de: "Version", fr: "Version", he: "גרסה", pt: "Versão", tr: "Sürüm").dict,
    "settings.reset.stats": Tr(zh: "重置统计", en: "Reset Stats", hant: "重設統計", ja: "記録をリセット", ko: "통계 초기화", es: "Restablecer estadísticas", ar: "إعادة تعيين الإحصاءات", de: "Statistik zurücksetzen", fr: "Réinitialiser les stats", he: "אפס סטטיסטיקה", pt: "Redefinir estatísticas", tr: "İstatistiği sıfırla").dict,
    "settings.reset.stats.q": Tr(zh: "重置统计？", en: "Reset stats?", hant: "重設統計？", ja: "記録をリセットする？", ko: "통계를 초기화할까요?", es: "¿Restablecer estadísticas?", ar: "إعادة تعيين الإحصاءات؟", de: "Statistik zurücksetzen?", fr: "Réinitialiser les stats ?", he: "לאפס סטטיסטיקה?", pt: "Redefinir estatísticas?", tr: "İstatistik sıfırlansın mı?").dict,
    "settings.reset.stats.msg": Tr(zh: "胜率、连胜等数据将被清空", en: "Win rate, streaks, etc. will be cleared", hant: "勝率、連勝等資料將被清空", ja: "勝率や連勝などが消えます", ko: "승률, 연승 등이 지워집니다", es: "Se borrarán victorias, rachas, etc.", ar: "ستُمسح نسبة الفوز والسلاسل وغيرها", de: "Siegquote, Serien usw. werden gelöscht", fr: "Taux de victoire, séries, etc. seront effacés", he: "אחוז ניצחון, רצפים וכו׳ יימחקו", pt: "Taxa de vitória, sequências etc. serão apagados", tr: "Galibiyet oranı, seriler vs. silinecek").dict,
    "settings.reset.all": Tr(zh: "重置全部进度", en: "Reset All Progress", hant: "重設全部進度", ja: "全進捗をリセット", ko: "모든 진행 초기화", es: "Borrar todo el progreso", ar: "مسح كل التقدم", de: "Allen Fortschritt löschen", fr: "Effacer toute la progression", he: "מחק את כל ההתקדמות", pt: "Apagar todo o progresso", tr: "Tüm ilerlemeyi sil").dict,
    "settings.reset.all.q": Tr(zh: "重置全部进度？", en: "Reset all progress?", hant: "重設全部進度？", ja: "全進捗をリセットする？", ko: "모든 진행을 초기화할까요?", es: "¿Borrar todo el progreso?", ar: "مسح كل التقدم؟", de: "Allen Fortschritt löschen?", fr: "Effacer toute la progression ?", he: "למחוק את כל ההתקדמות?", pt: "Apagar todo o progresso?", tr: "Tüm ilerleme silinsin mi?").dict,
    "settings.reset.all.msg": Tr(zh: "关卡、星数和统计将被永久清除", en: "Levels, stars, and stats will be permanently cleared", hant: "關卡、星數和統計將被永久清除", ja: "レベル、星、記録が完全に消えます", ko: "레벨, 별, 통계가 영구히 삭제됩니다", es: "Niveles, estrellas y estadísticas se borrarán para siempre", ar: "المستويات والنجوم والإحصاءات ستُمسح نهائيًا", de: "Level, Sterne und Statistik werden dauerhaft gelöscht", fr: "Niveaux, étoiles et stats seront définitivement effacés", he: "שלבים, כוכבים וסטטיסטיקה יימחקו לצמיתות", pt: "Níveis, estrelas e estatísticas serão apagados para sempre", tr: "Seviyeler, yıldızlar ve istatistik kalıcı olarak silinir").dict,
    "settings.cancel": Tr(zh: "取消", en: "Cancel", hant: "取消", ja: "キャンセル", ko: "취소", es: "Cancelar", ar: "إلغاء", de: "Abbrechen", fr: "Annuler", he: "ביטול", pt: "Cancelar", tr: "Vazgeç").dict,
    "settings.reset": Tr(zh: "重置", en: "Reset", hant: "重設", ja: "リセット", ko: "초기화", es: "Restablecer", ar: "إعادة تعيين", de: "Zurücksetzen", fr: "Réinitialiser", he: "איפוס", pt: "Redefinir", tr: "Sıfırla").dict,
    "settings.debug.pro": Tr(zh: "解锁 Pro（调试）", en: "Unlock Pro (Debug)", hant: "解鎖 Pro（除錯）", ja: "Pro解除（デバッグ）", ko: "Pro 해제 (디버그)", es: "Desbloquear Pro (debug)", ar: "فتح Pro (تصحيح)", de: "Pro freischalten (Debug)", fr: "Débloquer Pro (debug)", he: "פתח Pro (דיבאג)", pt: "Desbloquear Pro (debug)", tr: "Pro aç (hata ayıkla)").dict,
    "daily.streak": Tr(zh: "连续天数", en: "Day Streak", hant: "連續天數", ja: "連続日数", ko: "연속 일수", es: "Racha diaria", ar: "أيام متتالية", de: "Tages-Serie", fr: "Série de jours", he: "רצף ימים", pt: "Sequência diária", tr: "Gün serisi").dict,
    "daily.total": Tr(zh: "总计", en: "Total", hant: "總計", ja: "合計", ko: "합계", es: "Total", ar: "الإجمالي", de: "Gesamt", fr: "Total", he: "סה״כ", pt: "Total", tr: "Toplam").dict,
    "daily.leaderboard": Tr(zh: "排行榜", en: "Leaderboard", hant: "排行榜", ja: "ランキング", ko: "리더보드", es: "Clasificación", ar: "لوحة المتصدرين", de: "Rangliste", fr: "Classement", he: "לוח מובילים", pt: "Ranking", tr: "Sıralama").dict,
    "tutorial.back": Tr(zh: "返回", en: "Back", hant: "返回", ja: "戻る", ko: "뒤로", es: "Atrás", ar: "رجوع", de: "Zurück", fr: "Retour", he: "חזרה", pt: "Voltar", tr: "Geri").dict,
    "tutorial.go": Tr(zh: "开始！", en: "Start!", hant: "開始！", ja: "スタート！", ko: "시작!", es: "¡Empezar!", ar: "ابدأ!", de: "Los!", fr: "C’est parti !", he: "יאללה!", pt: "Começar!", tr: "Başla!").dict,
    "tutorial.star.speed": Tr(zh: "速通", en: "Speed", hant: "速通", ja: "最速", ko: "최속", es: "Rápido", ar: "سرعة", de: "Tempo", fr: "Rapide", he: "מהירות", pt: "Rápido", tr: "Hız").dict,
    "tutorial.star.good": Tr(zh: "良好", en: "Good", hant: "良好", ja: "良い", ko: "좋음", es: "Bien", ar: "جيد", de: "Gut", fr: "Bien", he: "טוב", pt: "Bom", tr: "İyi").dict,
    "tutorial.star.pass": Tr(zh: "通过", en: "Pass", hant: "通過", ja: "クリア", ko: "통과", es: "Aprobado", ar: "نجاح", de: "Bestanden", fr: "Réussi", he: "עבר", pt: "Passou", tr: "Geçti").dict,
    "tutorial.ex1": Tr(zh: "1 个位置对，2 个颜色对位置错，1 个不在密码中", en: "1 right spot, 2 right color wrong spot, 1 not in code", hant: "1 個位置對，2 個顏色對位置錯，1 個不在密碼中", ja: "位置正解1、色だけ正解2、コードにない色1", ko: "위치 맞음 1, 색만 맞음 2, 암호에 없음 1", es: "1 sitio bien, 2 color bien sitio mal, 1 fuera", ar: "موضع واحد صحيح، لونان صحيحان بموضع خطأ، واحد ليس في الرمز", de: "1 richtiger Platz, 2 richtige Farbe falscher Platz, 1 nicht im Code", fr: "1 bon emplacement, 2 bonnes couleurs mal placées, 1 hors du code", he: "מקום נכון 1, צבע נכון מקום שגוי 2, לא בקוד 1", pt: "1 lugar certo, 2 cor certa lugar errado, 1 fora do código", tr: "1 doğru yer, 2 doğru renk yanlış yer, 1 kodda yok").dict,
    "tutorial.ex2": Tr(zh: "全对！密码破译成功！", en: "All correct! Code cracked!", hant: "全對！密碼破譯成功！", ja: "全部正解！解読成功！", ko: "전부 맞음! 해독 성공!", es: "¡Todo bien! ¡Código descifrado!", ar: "الكل صحيح! فُك الرمز!", de: "Alles richtig! Code geknackt!", fr: "Tout juste ! Code cassé !", he: "הכול נכון! הקוד פוצח!", pt: "Tudo certo! Código decifrado!", tr: "Hepsi doğru! Kod kırıldı!").dict,
    "tutorial.dot.exact": Tr(zh: "位置对", en: "Right spot", hant: "位置對", ja: "位置正解", ko: "위치 맞음", es: "Sitio bien", ar: "المكان صحيح", de: "Richtiger Platz", fr: "Bon endroit", he: "מקום נכון", pt: "Lugar certo", tr: "Doğru yer").dict,
    "tutorial.dot.partial": Tr(zh: "颜色对、位置错", en: "Right color, wrong spot", hant: "顏色對、位置錯", ja: "色○ 位置×", ko: "색 맞음, 위치 다름", es: "Color bien, sitio mal", ar: "لون صحيح، مكان خطأ", de: "Farbe richtig, Platz falsch", fr: "Bonne couleur, mauvais endroit", he: "צבע נכון, מקום שגוי", pt: "Cor certa, lugar errado", tr: "Doğru renk, yanlış yer").dict,
    "tutorial.dot.miss": Tr(zh: "不在密码中", en: "Not in code", hant: "不在密碼中", ja: "コードにない", ko: "암호에 없음", es: "No está", ar: "ليس في الرمز", de: "Nicht im Code", fr: "Pas dans le code", he: "לא בקוד", pt: "Não está no código", tr: "Kodda yok").dict,
    "tutorial.notes": Tr(zh: "笔记", en: "Notes", hant: "筆記", ja: "メモ", ko: "노트", es: "Notas", ar: "ملاحظات", de: "Notizen", fr: "Notes", he: "פתקים", pt: "Notas", tr: "Notlar").dict,
    "tutorial.notes.d": Tr(zh: "用笔记记下推理\n排除的颜色不能再选", en: "Use notes to track your deductions\nEliminated colors are disabled in picker", hant: "用筆記記下推理\n排除的顏色不能再選", ja: "メモで推理を残そう\n除外した色は選べなくなる", ko: "노트로 추론을 기록하세요\n제외한 색은 고를 수 없습니다", es: "Usa notas para tus deducciones\nLos colores eliminados no se pueden elegir", ar: "سجّل استدلالك في الملاحظات\nالألوان المستبعدة تُعطَّل في المنتقي", de: "Notiere deine Schlüsse\nAusgeschlossene Farben sind im Picker deaktiviert", fr: "Note tes déductions\nLes couleurs éliminées sont désactivées", he: "רשום היסקים בפתקים\nצבעים שנפסלו מנוטרלים בבורר", pt: "Anote suas deduções\nCores eliminadas ficam desativadas", tr: "Çıkarımlarını not et\nElendi renkler seçicide kilitlenir").dict,
    "tutorial.notes.x": Tr(zh: "点格子：标为排除", en: "Tap cell: mark as eliminated", hant: "點格子：標為排除", ja: "マスをタップ：除外", ko: "칸을 탭: 제외로 표시", es: "Toca celda: marcar eliminado", ar: "اضغط الخانة: استبعاد", de: "Zelle tippen: ausschließen", fr: "Touche une case : éliminer", he: "הקש תא: סמן כפסול", pt: "Toque a célula: marcar eliminado", tr: "Hücreye dokun: ele").dict,
    "tutorial.notes.check": Tr(zh: "再点：标为确认", en: "Tap again: mark as confirmed", hant: "再點：標為確認", ja: "もう一度：確定", ko: "다시 탭: 확정", es: "Toca otra vez: confirmar", ar: "اضغط مجددًا: تأكيد", de: "Nochmal tippen: bestätigen", fr: "Touche encore : confirmer", he: "הקש שוב: אשר", pt: "Toque de novo: confirmar", tr: "Tekrar dokun: onayla").dict,
    "tutorial.notes.row": Tr(zh: "点色钉：切换整行", en: "Tap color peg: toggle entire row", hant: "點色釘：切換整行", ja: "色ペグ：行を切り替え", ko: "색 핀을 탭: 행 전환", es: "Toca ficha: cambia toda la fila", ar: "اضغط الوتد: تبديل الصف كله", de: "Farbstift tippen: ganze Zeile", fr: "Touche un pion : toute la ligne", he: "הקש יתד צבע: כל השורה", pt: "Toque o pino: a linha inteira", tr: "Renk çivisine dokun: tüm satır").dict,
    "tutorial.notes.col": Tr(zh: "点 P1/P2…：切换整列", en: "Tap P1/P2...: toggle entire column", hant: "點 P1/P2…：切換整列", ja: "P1/P2…：列を切り替え", ko: "P1/P2…를 탭: 열 전환", es: "Toca P1/P2…: cambia la columna", ar: "اضغط P1/P2…: تبديل العمود", de: "P1/P2… tippen: ganze Spalte", fr: "Touche P1/P2… : toute la colonne", he: "הקש P1/P2…: כל העמודה", pt: "Toque P1/P2…: a coluna inteira", tr: "P1/P2…: tüm sütun").dict,
    "tutorial.hints": Tr(zh: "提示", en: "Hints", hant: "提示", ja: "ヒント", ko: "힌트", es: "Pistas", ar: "تلميحات", de: "Tipps", fr: "Indices", he: "רמזים", pt: "Dicas", tr: "İpuçları").dict,
    "tutorial.hints.coins": Tr(zh: "提示币", en: "Hint Coins", hant: "提示幣", ja: "ヒントコイン", ko: "힌트 코인", es: "Monedas de pista", ar: "عملات التلميح", de: "Tipp-Münzen", fr: "Pièces d’indice", he: "מטבעות רמז", pt: "Moedas de dica", tr: "İpucu jetonu").dict,
    "tutorial.hints.spend": Tr(zh: "花 1 枚换一次逻辑提示", en: "Spend 1 coin for a logical deduction", hant: "花 1 枚換一次邏輯提示", ja: "1枚で論理ヒント1回", ko: "코인 1개로 논리 힌트 1회", es: "Gasta 1 moneda por una deducción", ar: "اصرف عملة واحدة لاستدلال منطقي", de: "1 Münze für eine logische Folgerung", fr: "Dépense 1 pièce pour une déduction", he: "בזבז מטבע אחד להיסק לוגי", pt: "Gaste 1 moeda por uma dedução", tr: "1 jetonla mantıksal çıkarım").dict,
    "tutorial.hints.earn": Tr(zh: "怎么获得", en: "How to earn", hant: "怎麼獲得", ja: "入手方法", ko: "얻는 법", es: "Cómo conseguirlas", ar: "كيف تكسب", de: "So verdienen", fr: "Comment en gagner", he: "איך מרוויחים", pt: "Como conseguir", tr: "Nasıl kazanılır").dict,
    "tutorial.hints.win": Tr(zh: "赢 3 局", en: "Win 3 games", hant: "贏 3 局", ja: "3勝する", ko: "3판 승리", es: "Gana 3 partidas", ar: "اربح 3 جولات", de: "3 Spiele gewinnen", fr: "Gagne 3 parties", he: "נצח 3 משחקים", pt: "Vença 3 partidas", tr: "3 oyun kazan").dict,
    "tutorial.hints.login": Tr(zh: "连续登录 2 天", en: "Login 2 days in a row", hant: "連續登入 2 天", ja: "2日連続で起動", ko: "2일 연속 접속", es: "Entra 2 días seguidos", ar: "سجّل يومين متتاليين", de: "2 Tage hintereinander öffnen", fr: "Ouvre 2 jours de suite", he: "היכנס יומיים ברצף", pt: "Entre 2 dias seguidos", tr: "2 gün üst üste aç").dict,
    "tutorial.hints.reward": Tr(zh: "+1 枚", en: "+1 coin", hant: "+1 枚", ja: "+1枚", ko: "+1개", es: "+1 moneda", ar: "+1 عملة", de: "+1 Münze", fr: "+1 pièce", he: "+1 מטבע", pt: "+1 moeda", tr: "+1 jeton").dict,
    "tutorial.hints.do": Tr(zh: "提示会做什么", en: "What hints do", hant: "提示會做什麼", ja: "ヒントの内容", ko: "힌트가 하는 일", es: "Qué hacen las pistas", ar: "ماذا تفعل التلميحات", de: "Was Tipps tun", fr: "Ce que font les indices", he: "מה הרמזים עושים", pt: "O que as dicas fazem", tr: "İpuçları ne yapar").dict,
    "tutorial.hints.do1": Tr(zh: "从这个位置排除错误颜色", en: "Eliminate wrong colors from a position", hant: "從這個位置排除錯誤顏色", ja: "その位置から間違った色を除外", ko: "그 칸에서 틀린 색을 제외", es: "Quita colores malos de una posición", ar: "استبعد الألوان الخطأ من موضع", de: "Falsche Farben an einer Position streichen", fr: "Élimine les mauvaises couleurs d’une position", he: "פסול צבעים שגויים מעמדה", pt: "Elimina cores erradas de uma posição", tr: "Bir konumdan yanlış renkleri ele").dict,
    "tutorial.hints.do2": Tr(zh: "剩余很少时，确认正确颜色", en: "Or confirm the correct color if few remain", hant: "剩餘很少時，確認正確顏色", ja: "残りが少なければ正しい色を確定", ko: "남은 색이 적으면 올바른 색을 확정", es: "O confirma el color si quedan pocos", ar: "أو أكّد اللون الصحيح إن بقي القليل", de: "Oder die richtige Farbe bestätigen, wenn wenig übrig", fr: "Ou confirme la bonne couleur s’il en reste peu", he: "או אשר את הצבע הנכון אם נשארו מעט", pt: "Ou confirma a cor certa se restam poucas", tr: "Az kaldıysa doğru rengi onayla").dict,
    "tutorial.hints.do3": Tr(zh: "帮你推理，不会直接给出答案", en: "Guides your logic — doesn't solve for you", hant: "幫你推理，不會直接給出答案", ja: "考え方を助ける。答えは教えない", ko: "추론을 도울 뿐, 답을 주지는 않습니다", es: "Guía tu lógica; no resuelve por ti", ar: "يرشد منطقك — لا يحل عنك", de: "Leitet deine Logik — löst nicht für dich", fr: "Guide ta logique — ne résout pas à ta place", he: "מדריך את ההיגיון — לא פותר במקומך", pt: "Guia sua lógica — não resolve por você", tr: "Mantığını yönlendirir — senin yerine çözmez").dict,
    "tutorial.lie.r1": Tr(zh: "恰好有 1 条反馈是假的", en: "Exactly 1 feedback is fake", hant: "恰好有 1 條回饋是假的", ja: "手がかりの嘘はちょうど1つ", ko: "가짜 단서는 정확히 1개", es: "Exactamente 1 pista es falsa", ar: "دليل واحد بالضبط مزيف", de: "Genau 1 Hinweis ist falsch", fr: "Exactement 1 indice est faux", he: "בדיוק רמז אחד מזויף", pt: "Exatamente 1 pista é falsa", tr: "Tam 1 ipucu sahte").dict,
    "tutorial.lie.r2": Tr(zh: "假线索与真相最多差 1", en: "Lie differs from truth by ≤1", hant: "假線索與真相最多差 1", ja: "嘘と真実の差は1以内", ko: "거짓과 진실의 차이는 1 이하", es: "La mentira difiere de la verdad en ≤1", ar: "الكذبة تختلف عن الحقيقة بـ ≤1", de: "Lüge weicht von der Wahrheit um ≤1 ab", fr: "Le mensonge diffère de la vérité de ≤1", he: "השקר שונה מהאמת ב־≤1", pt: "A mentira difere da verdade em ≤1", tr: "Yalan gerçekten en fazla 1 sapar").dict,
    "tutorial.lie.r3": Tr(zh: "猜中密码的那一步一定是真的", en: "The winning guess is always truthful", hant: "猜中密碼的那一步一定是真的", ja: "正解の手の手がかりは必ず本当", ko: "정답 수의 단서는 항상 참", es: "La jugada ganadora siempre es honesta", ar: "تخمين الفوز صادق دائمًا", de: "Der Gewinnzug ist immer wahr", fr: "Le coup gagnant est toujours honnête", he: "ניחוש הניצחון תמיד אמיתי", pt: "O palpite vencedor é sempre honesto", tr: "Kazanan tahmin her zaman doğru").dict,
    "tutorial.lie.r4": Tr(zh: "找出哪一条反馈在说谎", en: "Figure out which feedback was fake", hant: "找出哪一條回饋在說謊", ja: "どの手がかりが嘘かを見抜く", ko: "어떤 단서가 거짓인지 찾아내세요", es: "Averigua qué pista mentía", ar: "اعرف أي دليل كان مزيفًا", de: "Finde heraus, welcher Hinweis gelogen hat", fr: "Trouve quel indice mentait", he: "גלה איזה רמז שיקר", pt: "Descubra qual pista mentia", tr: "Hangi ipucunun yalan olduğunu bul").dict,
    "tutorial.tips": Tr(zh: "技巧", en: "Tips", hant: "技巧", ja: "コツ", ko: "팁", es: "Consejos", ar: "نصائح", de: "Tipps", fr: "Astuces", he: "טיפים", pt: "Dicas", tr: "İpuçları").dict,
    "tutorial.tips.elim": Tr(zh: "排除", en: "Elimination", hant: "排除", ja: "除外", ko: "제외", es: "Eliminación", ar: "الاستبعاد", de: "Ausschluss", fr: "Élimination", he: "פסילה", pt: "Eliminação", tr: "Eleme").dict,
    "tutorial.tips.elim.d": Tr(zh: "换不同颜色，找出哪些在密码里", en: "Try different colors to find which ones are in the code", hant: "換不同顏色，找出哪些在密碼裡", ja: "色を変えて、コードに含まれる色を探す", ko: "다른 색을 써서 암호에 있는 색을 찾으세요", es: "Prueba colores distintos para ver cuáles están", ar: "جرّب ألوانًا مختلفة لتعرف أيها في الرمز", de: "Probiere andere Farben, um zu sehen, welche im Code sind", fr: "Essaie d’autres couleurs pour voir lesquelles sont dans le code", he: "נסה צבעים שונים כדי לדעת אילו בקוד", pt: "Teste cores diferentes para ver quais estão no código", tr: "Farklı renk dene, hangileri kodda gör").dict,
    "tutorial.tips.compare": Tr(zh: "对比", en: "Compare", hant: "對比", ja: "比較", ko: "비교", es: "Compara", ar: "المقارنة", de: "Vergleichen", fr: "Comparer", he: "השוואה", pt: "Comparar", tr: "Karşılaştır").dict,
    "tutorial.tips.compare.d": Tr(zh: "对比各步反馈，缩小范围", en: "Compare feedback between guesses to narrow down", hant: "對比各步回饋，縮小範圍", ja: "各手の手がかりを比べて絞り込む", ko: "각 수의 단서를 비교해 범위를 좁히세요", es: "Compara pistas entre intentos para acotar", ar: "قارن الأدلة بين التخمينات لتضييق النطاق", de: "Vergleiche Hinweise zwischen Zügen, um einzugrenzen", fr: "Compare les indices entre les essais pour restreindre", he: "השווה רמזים בין ניחושים כדי לצמצם", pt: "Compare pistas entre palpites para afunilar", tr: "Tahminlerin ipuçlarını karşılaştırıp daralt").dict,
    "duel.tap": Tr(zh: "点颜色添加，点空位删除", en: "Tap color to add, tap slot to remove", hant: "點顏色新增，點空位刪除", ja: "色をタップで追加、スロットで削除", ko: "색을 눌러 추가, 칸을 눌러 제거", es: "Toca color para añadir, hueco para quitar", ar: "اضغط لونًا للإضافة، خانة للحذف", de: "Farbe tippen zum Hinzufügen, Slot zum Entfernen", fr: "Touche une couleur pour ajouter, un creux pour retirer", he: "הקש צבע להוספה, משבצת להסרה", pt: "Toque cor para adicionar, espaço para remover", tr: "Renke dokun ekle, yuvaya dokun sil").dict,
    "duel.rule1": Tr(zh: "1. 玩家 1 秘密设置一组颜色密码", en: "1. Player 1 secretly sets a color code", hant: "1. 玩家 1 秘密設定一組顏色密碼", ja: "1. プレイヤー1がこっそりコードを決める", ko: "1. 플레이어 1이 몰래 색 암호를 정합니다", es: "1. El jugador 1 pone un código en secreto", ar: "1. اللاعب 1 يضع رمز ألوان سرًا", de: "1. Spieler 1 legt heimlich einen Farbcode", fr: "1. Le joueur 1 pose un code en secret", he: "1. שחקן 1 קובע קוד צבעים בסתר", pt: "1. O jogador 1 define um código em segredo", tr: "1. Oyuncu 1 gizlice renk kodu koyar").dict,
    "duel.rule2": Tr(zh: "2. 把手机交给玩家 2", en: "2. Pass the phone to Player 2", hant: "2. 把手機交給玩家 2", ja: "2. スマホをプレイヤー2に渡す", ko: "2. 휴대폰을 플레이어 2에게 넘깁니다", es: "2. Pasa el teléfono al jugador 2", ar: "2. سلّم الهاتف للاعب 2", de: "2. Gib das Handy an Spieler 2", fr: "2. Passe le téléphone au joueur 2", he: "2. העבר את הטלפון לשחקן 2", pt: "2. Passe o telefone ao jogador 2", tr: "2. Telefonu 2. oyuncuya ver").dict,
    "duel.rule3": Tr(zh: "3. 玩家 2 在次数内破解密码", en: "3. Player 2 cracks the code within the limit", hant: "3. 玩家 2 在次數內破解密碼", ja: "3. プレイヤー2が制限手数で解読", ko: "3. 플레이어 2가 제한 안에 해독합니다", es: "3. El jugador 2 lo descifra a tiempo", ar: "3. اللاعب 2 يفك الرمز ضمن الحد", de: "3. Spieler 2 knackt den Code innerhalb des Limits", fr: "3. Le joueur 2 casse le code dans la limite", he: "3. שחקן 2 מפצח את הקוד במגבלה", pt: "3. O jogador 2 decifra a tempo", tr: "3. Oyuncu 2 kodu sınır içinde çözer").dict,
    "duel.rule4": Tr(zh: "4. 步数越少越好！", en: "4. Fewer steps = better!", hant: "4. 步數越少越好！", ja: "4. 手数が少ないほど良い！", ko: "4. 수가 적을수록 좋습니다!", es: "4. ¡Menos pasos es mejor!", ar: "4. كلما قلت الخطوات كان أفضل!", de: "4. Weniger Züge = besser!", fr: "4. Moins de coups = mieux !", he: "4. פחות מהלכים = יותר טוב!", pt: "4. Menos passos é melhor!", tr: "4. Daha az hamle daha iyi!").dict,
    "settings.unlocked": Tr(zh: "已解锁", en: "Unlocked", hant: "已解鎖", ja: "解除済み", ko: "해제됨", es: "Desbloqueado", ar: "مفتوح", de: "Freigeschaltet", fr: "Débloqué", he: "נפתח", pt: "Desbloqueado", tr: "Açık").dict,
    "param.fake": Tr(zh: "虚假反馈", en: "Fake feedback", hant: "虛假回饋", ja: "嘘の手がかり", ko: "가짜 단서", es: "Pista falsa", ar: "دليل مزيف", de: "Falscher Hinweis", fr: "Indice faux", he: "רמז מזויף", pt: "Pista falsa", tr: "Sahte ipucu").dict,
    "level.start": Tr(zh: "开始", en: "Start", hant: "開始", ja: "始める", ko: "시작", es: "Empezar", ar: "ابدأ", de: "Start", fr: "Commencer", he: "התחל", pt: "Começar", tr: "Başla").dict,
    "challenge.from": Tr(zh: "来自好友的挑战", en: "Challenge from", hant: "來自好友的挑戰", ja: "友だちからの挑戦", ko: "친구의 도전장", es: "Reto de", ar: "تحدٍ من", de: "Herausforderung von", fr: "Défi de", he: "אתגר מאת", pt: "Desafio de", tr: "Meydan okuma:").dict,
    "challenge.prompt": Tr(zh: "能破解他们的密码吗？", en: "Can you crack their code?", hant: "能破解他們的密碼嗎？", ja: "そのコード、解読できる？", ko: "그 암호를 풀 수 있나요?", es: "¿Puedes descifrar su código?", ar: "هل تفك رمزهم؟", de: "Kannst du ihren Code knacken?", fr: "Tu peux casser leur code ?", he: "תוכל לפצח את הקוד שלהם?", pt: "Consegue decifrar o código deles?", tr: "Onların kodunu kırabilir misin?").dict,
    "challenge.accept": Tr(zh: "接受挑战", en: "Accept Challenge", hant: "接受挑戰", ja: "挑戦を受ける", ko: "도전 수락", es: "Aceptar reto", ar: "قبول التحدي", de: "Annehmen", fr: "Accepter le défi", he: "קבל אתגר", pt: "Aceitar desafio", tr: "Görevi kabul et").dict,
    "challenge.title": Tr(zh: "挑战", en: "Challenge", hant: "挑戰", ja: "挑戦", ko: "도전", es: "Reto", ar: "تحدٍ", de: "Herausforderung", fr: "Défi", he: "אתגר", pt: "Desafio", tr: "Meydan okuma").dict,
    "challenge.lie": Tr(zh: "谎言模式 — 一条反馈可能是假的！", en: "Lie Mode — one feedback may be fake!", hant: "謊言模式 — 一條回饋可能是假的！", ja: "嘘モード — 手がかりの1つが嘘かも！", ko: "거짓말 모드 — 단서 하나가 가짜일 수 있습니다!", es: "Modo Mentira — ¡una pista puede ser falsa!", ar: "وضع الكذب — قد يكون أحد الأدلة مزيفًا!", de: "Lügenmodus — ein Hinweis kann falsch sein!", fr: "Mode Mensonge — un indice peut être faux !", he: "מצב שקר — רמז אחד עלול להיות מזויף!", pt: "Modo Mentira — uma pista pode ser falsa!", tr: "Yalan modu — bir ipucu sahte olabilir!").dict,
]

func L(_ key: String) -> String {
    localizedTemplate(key)
}

func L(_ key: String, _ args: CVarArg...) -> String {
    String(format: localizedTemplate(key), arguments: args)
}
